/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DwollaError } from "./dwollaerror.js";

export type BadRequestSchemaErrorData = {
  code: string;
  message: string;
  embedded?: models.BadRequestSchemaEmbedded | undefined;
};

export class BadRequestSchemaError extends DwollaError {
  code: string;
  embedded?: models.BadRequestSchemaEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: BadRequestSchemaErrorData;

  constructor(
    err: BadRequestSchemaErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "BadRequestSchemaError";
  }
}

/** @internal */
export const BadRequestSchemaError$inboundSchema: z.ZodType<
  BadRequestSchemaError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() => models.BadRequestSchemaEmbedded$inboundSchema)
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new BadRequestSchemaError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type BadRequestSchemaError$Outbound = {
  code: string;
  message: string;
  _embedded?: models.BadRequestSchemaEmbedded$Outbound | undefined;
};

/** @internal */
export const BadRequestSchemaError$outboundSchema: z.ZodType<
  BadRequestSchemaError$Outbound,
  z.ZodTypeDef,
  BadRequestSchemaError
> = z.instanceof(BadRequestSchemaError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      code: z.string(),
      message: z.string(),
      embedded: z.lazy(() => models.BadRequestSchemaEmbedded$outboundSchema)
        .optional(),
    }).transform((v) => {
      return remap$(v, {
        embedded: "_embedded",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestSchemaError$ {
  /** @deprecated use `BadRequestSchemaError$inboundSchema` instead. */
  export const inboundSchema = BadRequestSchemaError$inboundSchema;
  /** @deprecated use `BadRequestSchemaError$outboundSchema` instead. */
  export const outboundSchema = BadRequestSchemaError$outboundSchema;
  /** @deprecated use `BadRequestSchemaError$Outbound` instead. */
  export type Outbound = BadRequestSchemaError$Outbound;
}
