/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { DwollaError } from "./dwollaerror.js";

/**
 * Not Found
 */
export type CreateLabelReallocationNotFoundDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * Not Found
 */
export class CreateLabelReallocationNotFoundDwollaV1HalJSONError
  extends DwollaError
{
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateLabelReallocationNotFoundDwollaV1HalJSONErrorData;

  constructor(
    err: CreateLabelReallocationNotFoundDwollaV1HalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "CreateLabelReallocationNotFoundDwollaV1HalJSONError";
  }
}

/**
 * Forbidden
 */
export type CreateLabelReallocationForbiddenDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * Forbidden
 */
export class CreateLabelReallocationForbiddenDwollaV1HalJSONError
  extends DwollaError
{
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateLabelReallocationForbiddenDwollaV1HalJSONErrorData;

  constructor(
    err: CreateLabelReallocationForbiddenDwollaV1HalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "CreateLabelReallocationForbiddenDwollaV1HalJSONError";
  }
}

/** @internal */
export const CreateLabelReallocationNotFoundDwollaV1HalJSONError$inboundSchema:
  z.ZodType<
    CreateLabelReallocationNotFoundDwollaV1HalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new CreateLabelReallocationNotFoundDwollaV1HalJSONError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const CreateLabelReallocationForbiddenDwollaV1HalJSONError$inboundSchema:
  z.ZodType<
    CreateLabelReallocationForbiddenDwollaV1HalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new CreateLabelReallocationForbiddenDwollaV1HalJSONError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
