/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/union.js";
import { DwollaError } from "./dwollaerror.js";
import {
  InvalidExchangeError,
  InvalidExchangeError$inboundSchema,
} from "./invalidexchangeerror.js";
import {
  InvalidExchangeTokenError,
  InvalidExchangeTokenError$inboundSchema,
} from "./invalidexchangetokenerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * Invalid Scope
 */
export type CreateAccountExchangeDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * Invalid Scope
 */
export class CreateAccountExchangeDwollaV1HalJSONError extends DwollaError {
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateAccountExchangeDwollaV1HalJSONErrorData;

  constructor(
    err: CreateAccountExchangeDwollaV1HalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "CreateAccountExchangeDwollaV1HalJSONError";
  }
}

/**
 * Bad Request
 */
export type CreateAccountExchangeDwollaV1HalJSON =
  | InvalidExchangeTokenError
  | InvalidExchangeError;

/** @internal */
export const CreateAccountExchangeDwollaV1HalJSONError$inboundSchema: z.ZodType<
  CreateAccountExchangeDwollaV1HalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CreateAccountExchangeDwollaV1HalJSONError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const CreateAccountExchangeDwollaV1HalJSON$inboundSchema: z.ZodType<
  CreateAccountExchangeDwollaV1HalJSON,
  z.ZodTypeDef,
  unknown
> = smartUnion([
  InvalidExchangeTokenError$inboundSchema,
  InvalidExchangeError$inboundSchema,
]);

export function createAccountExchangeDwollaV1HalJSONFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountExchangeDwollaV1HalJSON, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateAccountExchangeDwollaV1HalJSON$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountExchangeDwollaV1HalJSON' from JSON`,
  );
}
