/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * not found
 */
export type CreateCustomerFundingSourceTokenDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * not found
 */
export class CreateCustomerFundingSourceTokenDwollaV1HalJSONError
  extends Error
{
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CreateCustomerFundingSourceTokenDwollaV1HalJSONErrorData;

  constructor(err: CreateCustomerFundingSourceTokenDwollaV1HalJSONErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.code != null) this.code = err.code;

    this.name = "CreateCustomerFundingSourceTokenDwollaV1HalJSONError";
  }
}

/** @internal */
export const CreateCustomerFundingSourceTokenDwollaV1HalJSONError$inboundSchema:
  z.ZodType<
    CreateCustomerFundingSourceTokenDwollaV1HalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  })
    .transform((v) => {
      return new CreateCustomerFundingSourceTokenDwollaV1HalJSONError(v);
    });

/** @internal */
export type CreateCustomerFundingSourceTokenDwollaV1HalJSONError$Outbound = {
  code?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const CreateCustomerFundingSourceTokenDwollaV1HalJSONError$outboundSchema:
  z.ZodType<
    CreateCustomerFundingSourceTokenDwollaV1HalJSONError$Outbound,
    z.ZodTypeDef,
    CreateCustomerFundingSourceTokenDwollaV1HalJSONError
  > = z.instanceof(CreateCustomerFundingSourceTokenDwollaV1HalJSONError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: z.string().optional(),
      message: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateCustomerFundingSourceTokenDwollaV1HalJSONError$ {
  /** @deprecated use `CreateCustomerFundingSourceTokenDwollaV1HalJSONError$inboundSchema` instead. */
  export const inboundSchema =
    CreateCustomerFundingSourceTokenDwollaV1HalJSONError$inboundSchema;
  /** @deprecated use `CreateCustomerFundingSourceTokenDwollaV1HalJSONError$outboundSchema` instead. */
  export const outboundSchema =
    CreateCustomerFundingSourceTokenDwollaV1HalJSONError$outboundSchema;
  /** @deprecated use `CreateCustomerFundingSourceTokenDwollaV1HalJSONError$Outbound` instead. */
  export type Outbound =
    CreateCustomerFundingSourceTokenDwollaV1HalJSONError$Outbound;
}
