/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DwollaError } from "./dwollaerror.js";

/**
 * forbidden
 */
export type CustomerCreationForbiddenResponseErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * forbidden
 */
export class CustomerCreationForbiddenResponseError extends DwollaError {
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CustomerCreationForbiddenResponseErrorData;

  constructor(
    err: CustomerCreationForbiddenResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "CustomerCreationForbiddenResponseError";
  }
}

/** @internal */
export const CustomerCreationForbiddenResponseError$inboundSchema: z.ZodType<
  CustomerCreationForbiddenResponseError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CustomerCreationForbiddenResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CustomerCreationForbiddenResponseError$Outbound = {
  code?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const CustomerCreationForbiddenResponseError$outboundSchema: z.ZodType<
  CustomerCreationForbiddenResponseError$Outbound,
  z.ZodTypeDef,
  CustomerCreationForbiddenResponseError
> = z.instanceof(CustomerCreationForbiddenResponseError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerCreationForbiddenResponseError$ {
  /** @deprecated use `CustomerCreationForbiddenResponseError$inboundSchema` instead. */
  export const inboundSchema =
    CustomerCreationForbiddenResponseError$inboundSchema;
  /** @deprecated use `CustomerCreationForbiddenResponseError$outboundSchema` instead. */
  export const outboundSchema =
    CustomerCreationForbiddenResponseError$outboundSchema;
  /** @deprecated use `CustomerCreationForbiddenResponseError$Outbound` instead. */
  export type Outbound = CustomerCreationForbiddenResponseError$Outbound;
}
