/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DwollaError } from "./dwollaerror.js";

/**
 * Bad Request
 */
export type CustomerCreationBadRequestResponseErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * Bad Request
 */
export class CustomerCreationBadRequestResponseError extends DwollaError {
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: CustomerCreationBadRequestResponseErrorData;

  constructor(
    err: CustomerCreationBadRequestResponseErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "CustomerCreationBadRequestResponseError";
  }
}

/** @internal */
export const CustomerCreationBadRequestResponseError$inboundSchema: z.ZodType<
  CustomerCreationBadRequestResponseError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CustomerCreationBadRequestResponseError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CustomerCreationBadRequestResponseError$Outbound = {
  code?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const CustomerCreationBadRequestResponseError$outboundSchema: z.ZodType<
  CustomerCreationBadRequestResponseError$Outbound,
  z.ZodTypeDef,
  CustomerCreationBadRequestResponseError
> = z.instanceof(CustomerCreationBadRequestResponseError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerCreationBadRequestResponseError$ {
  /** @deprecated use `CustomerCreationBadRequestResponseError$inboundSchema` instead. */
  export const inboundSchema =
    CustomerCreationBadRequestResponseError$inboundSchema;
  /** @deprecated use `CustomerCreationBadRequestResponseError$outboundSchema` instead. */
  export const outboundSchema =
    CustomerCreationBadRequestResponseError$outboundSchema;
  /** @deprecated use `CustomerCreationBadRequestResponseError$Outbound` instead. */
  export type Outbound = CustomerCreationBadRequestResponseError$Outbound;
}
