/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type DestinationAddendaMaxLengthErrorData = {
  code: string;
  message: string;
  embedded?: models.DestinationAddendaMaxLengthErrorEmbedded | undefined;
};

export class DestinationAddendaMaxLengthError extends Error {
  code: string;
  embedded?: models.DestinationAddendaMaxLengthErrorEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: DestinationAddendaMaxLengthErrorData;

  constructor(err: DestinationAddendaMaxLengthErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "DestinationAddendaMaxLengthError";
  }
}

/** @internal */
export const DestinationAddendaMaxLengthError$inboundSchema: z.ZodType<
  DestinationAddendaMaxLengthError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() =>
    models.DestinationAddendaMaxLengthErrorEmbedded$inboundSchema
  ).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new DestinationAddendaMaxLengthError(remapped);
  });

/** @internal */
export type DestinationAddendaMaxLengthError$Outbound = {
  code: string;
  message: string;
  _embedded?:
    | models.DestinationAddendaMaxLengthErrorEmbedded$Outbound
    | undefined;
};

/** @internal */
export const DestinationAddendaMaxLengthError$outboundSchema: z.ZodType<
  DestinationAddendaMaxLengthError$Outbound,
  z.ZodTypeDef,
  DestinationAddendaMaxLengthError
> = z.instanceof(DestinationAddendaMaxLengthError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      code: z.string(),
      message: z.string(),
      embedded: z.lazy(() =>
        models.DestinationAddendaMaxLengthErrorEmbedded$outboundSchema
      ).optional(),
    }).transform((v) => {
      return remap$(v, {
        embedded: "_embedded",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DestinationAddendaMaxLengthError$ {
  /** @deprecated use `DestinationAddendaMaxLengthError$inboundSchema` instead. */
  export const inboundSchema = DestinationAddendaMaxLengthError$inboundSchema;
  /** @deprecated use `DestinationAddendaMaxLengthError$outboundSchema` instead. */
  export const outboundSchema = DestinationAddendaMaxLengthError$outboundSchema;
  /** @deprecated use `DestinationAddendaMaxLengthError$Outbound` instead. */
  export type Outbound = DestinationAddendaMaxLengthError$Outbound;
}
