/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DwollaError } from "./dwollaerror.js";

export type DestinationProcessingChannelNotSupportedErrorData = {
  code: string;
  message: string;
  embedded?:
    | models.DestinationProcessingChannelNotSupportedErrorEmbedded
    | undefined;
};

export class DestinationProcessingChannelNotSupportedError extends DwollaError {
  code: string;
  embedded?:
    | models.DestinationProcessingChannelNotSupportedErrorEmbedded
    | undefined;

  /** The original data that was passed to this error instance. */
  data$: DestinationProcessingChannelNotSupportedErrorData;

  constructor(
    err: DestinationProcessingChannelNotSupportedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "DestinationProcessingChannelNotSupportedError";
  }
}

/** @internal */
export const DestinationProcessingChannelNotSupportedError$inboundSchema:
  z.ZodType<
    DestinationProcessingChannelNotSupportedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string(),
    message: z.string(),
    _embedded: z.lazy(() =>
      models.DestinationProcessingChannelNotSupportedErrorEmbedded$inboundSchema
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "_embedded": "embedded",
      });

      return new DestinationProcessingChannelNotSupportedError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
