/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { DwollaError } from "./dwollaerror.js";

/**
 * not found
 */
export type GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONErrorData =
  {
    code?: string | undefined;
    message?: string | undefined;
  };

/**
 * not found
 */
export class GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONError
  extends DwollaError
{
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONErrorData;

  constructor(
    err:
      GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name =
      "GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONError";
  }
}

/**
 * forbidden
 */
export type GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONErrorData =
  {
    code?: string | undefined;
    message?: string | undefined;
  };

/**
 * forbidden
 */
export class GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONError
  extends DwollaError
{
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONErrorData;

  constructor(
    err:
      GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name =
      "GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONError";
  }
}

/** @internal */
export const GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONError$inboundSchema:
  z.ZodType<
    GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetBeneficialOwnershipStatusForCustomerNotFoundDwollaV1HalJSONError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONError$inboundSchema:
  z.ZodType<
    GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetBeneficialOwnershipStatusForCustomerForbiddenDwollaV1HalJSONError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });
