/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { DwollaError } from "./dwollaerror.js";

/**
 * 404 Error
 */
export type GetKbaQuestionsDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * 404 Error
 */
export class GetKbaQuestionsDwollaV1HalJSONError extends DwollaError {
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetKbaQuestionsDwollaV1HalJSONErrorData;

  constructor(
    err: GetKbaQuestionsDwollaV1HalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "GetKbaQuestionsDwollaV1HalJSONError";
  }
}

/** @internal */
export const GetKbaQuestionsDwollaV1HalJSONError$inboundSchema: z.ZodType<
  GetKbaQuestionsDwollaV1HalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetKbaQuestionsDwollaV1HalJSONError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetKbaQuestionsDwollaV1HalJSONError$Outbound = {
  code?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const GetKbaQuestionsDwollaV1HalJSONError$outboundSchema: z.ZodType<
  GetKbaQuestionsDwollaV1HalJSONError$Outbound,
  z.ZodTypeDef,
  GetKbaQuestionsDwollaV1HalJSONError
> = z.instanceof(GetKbaQuestionsDwollaV1HalJSONError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetKbaQuestionsDwollaV1HalJSONError$ {
  /** @deprecated use `GetKbaQuestionsDwollaV1HalJSONError$inboundSchema` instead. */
  export const inboundSchema =
    GetKbaQuestionsDwollaV1HalJSONError$inboundSchema;
  /** @deprecated use `GetKbaQuestionsDwollaV1HalJSONError$outboundSchema` instead. */
  export const outboundSchema =
    GetKbaQuestionsDwollaV1HalJSONError$outboundSchema;
  /** @deprecated use `GetKbaQuestionsDwollaV1HalJSONError$Outbound` instead. */
  export type Outbound = GetKbaQuestionsDwollaV1HalJSONError$Outbound;
}
