/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { DwollaError } from "./dwollaerror.js";

/**
 * unauthorized
 */
export type GetRootDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * unauthorized
 */
export class GetRootDwollaV1HalJSONError extends DwollaError {
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetRootDwollaV1HalJSONErrorData;

  constructor(
    err: GetRootDwollaV1HalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;

    this.name = "GetRootDwollaV1HalJSONError";
  }
}

/** @internal */
export const GetRootDwollaV1HalJSONError$inboundSchema: z.ZodType<
  GetRootDwollaV1HalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetRootDwollaV1HalJSONError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
