/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DwollaError } from "./dwollaerror.js";

export type InvalidKbaSessionErrorData = {
  code: string;
  message: string;
};

export class InvalidKbaSessionError extends DwollaError {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: InvalidKbaSessionErrorData;

  constructor(
    err: InvalidKbaSessionErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "InvalidKbaSessionError";
  }
}

/** @internal */
export const InvalidKbaSessionError$inboundSchema: z.ZodType<
  InvalidKbaSessionError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InvalidKbaSessionError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type InvalidKbaSessionError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const InvalidKbaSessionError$outboundSchema: z.ZodType<
  InvalidKbaSessionError$Outbound,
  z.ZodTypeDef,
  InvalidKbaSessionError
> = z.instanceof(InvalidKbaSessionError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.string(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InvalidKbaSessionError$ {
  /** @deprecated use `InvalidKbaSessionError$inboundSchema` instead. */
  export const inboundSchema = InvalidKbaSessionError$inboundSchema;
  /** @deprecated use `InvalidKbaSessionError$outboundSchema` instead. */
  export const outboundSchema = InvalidKbaSessionError$outboundSchema;
  /** @deprecated use `InvalidKbaSessionError$Outbound` instead. */
  export type Outbound = InvalidKbaSessionError$Outbound;
}
