/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DwollaError } from "./dwollaerror.js";

export type InvalidFileTypeSchemaErrorData = {
  code: string;
  message: string;
};

export class InvalidFileTypeSchemaError extends DwollaError {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: InvalidFileTypeSchemaErrorData;

  constructor(
    err: InvalidFileTypeSchemaErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "InvalidFileTypeSchemaError";
  }
}

/** @internal */
export const InvalidFileTypeSchemaError$inboundSchema: z.ZodType<
  InvalidFileTypeSchemaError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InvalidFileTypeSchemaError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type InvalidFileTypeSchemaError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const InvalidFileTypeSchemaError$outboundSchema: z.ZodType<
  InvalidFileTypeSchemaError$Outbound,
  z.ZodTypeDef,
  InvalidFileTypeSchemaError
> = z.instanceof(InvalidFileTypeSchemaError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.string(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InvalidFileTypeSchemaError$ {
  /** @deprecated use `InvalidFileTypeSchemaError$inboundSchema` instead. */
  export const inboundSchema = InvalidFileTypeSchemaError$inboundSchema;
  /** @deprecated use `InvalidFileTypeSchemaError$outboundSchema` instead. */
  export const outboundSchema = InvalidFileTypeSchemaError$outboundSchema;
  /** @deprecated use `InvalidFileTypeSchemaError$Outbound` instead. */
  export type Outbound = InvalidFileTypeSchemaError$Outbound;
}
