/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { DwollaError } from "./dwollaerror.js";

export type InvalidExchangeTokenErrorData = {
  code: string;
  message: string;
};

export class InvalidExchangeTokenError extends DwollaError {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: InvalidExchangeTokenErrorData;

  constructor(
    err: InvalidExchangeTokenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "InvalidExchangeTokenError";
  }
}

/** @internal */
export const InvalidExchangeTokenError$inboundSchema: z.ZodType<
  InvalidExchangeTokenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InvalidExchangeTokenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
