/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * not found
 */
export type ListAccountMassPaymentsNotFoundDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * not found
 */
export class ListAccountMassPaymentsNotFoundDwollaV1HalJSONError extends Error {
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListAccountMassPaymentsNotFoundDwollaV1HalJSONErrorData;

  constructor(err: ListAccountMassPaymentsNotFoundDwollaV1HalJSONErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.code != null) this.code = err.code;

    this.name = "ListAccountMassPaymentsNotFoundDwollaV1HalJSONError";
  }
}

/**
 * forbidden
 */
export type ListAccountMassPaymentsForbiddenDwollaV1HalJSONErrorData = {
  code?: string | undefined;
  message?: string | undefined;
};

/**
 * forbidden
 */
export class ListAccountMassPaymentsForbiddenDwollaV1HalJSONError
  extends Error
{
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListAccountMassPaymentsForbiddenDwollaV1HalJSONErrorData;

  constructor(err: ListAccountMassPaymentsForbiddenDwollaV1HalJSONErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.code != null) this.code = err.code;

    this.name = "ListAccountMassPaymentsForbiddenDwollaV1HalJSONError";
  }
}

/** @internal */
export const ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$inboundSchema:
  z.ZodType<
    ListAccountMassPaymentsNotFoundDwollaV1HalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  })
    .transform((v) => {
      return new ListAccountMassPaymentsNotFoundDwollaV1HalJSONError(v);
    });

/** @internal */
export type ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$Outbound = {
  code?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$outboundSchema:
  z.ZodType<
    ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$Outbound,
    z.ZodTypeDef,
    ListAccountMassPaymentsNotFoundDwollaV1HalJSONError
  > = z.instanceof(ListAccountMassPaymentsNotFoundDwollaV1HalJSONError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: z.string().optional(),
      message: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$ {
  /** @deprecated use `ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$inboundSchema` instead. */
  export const inboundSchema =
    ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$inboundSchema;
  /** @deprecated use `ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$outboundSchema` instead. */
  export const outboundSchema =
    ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$outboundSchema;
  /** @deprecated use `ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$Outbound` instead. */
  export type Outbound =
    ListAccountMassPaymentsNotFoundDwollaV1HalJSONError$Outbound;
}

/** @internal */
export const ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$inboundSchema:
  z.ZodType<
    ListAccountMassPaymentsForbiddenDwollaV1HalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
  })
    .transform((v) => {
      return new ListAccountMassPaymentsForbiddenDwollaV1HalJSONError(v);
    });

/** @internal */
export type ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$Outbound = {
  code?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$outboundSchema:
  z.ZodType<
    ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$Outbound,
    z.ZodTypeDef,
    ListAccountMassPaymentsForbiddenDwollaV1HalJSONError
  > = z.instanceof(ListAccountMassPaymentsForbiddenDwollaV1HalJSONError)
    .transform(v => v.data$)
    .pipe(z.object({
      code: z.string().optional(),
      message: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$ {
  /** @deprecated use `ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$inboundSchema` instead. */
  export const inboundSchema =
    ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$inboundSchema;
  /** @deprecated use `ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$outboundSchema` instead. */
  export const outboundSchema =
    ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$outboundSchema;
  /** @deprecated use `ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$Outbound` instead. */
  export type Outbound =
    ListAccountMassPaymentsForbiddenDwollaV1HalJSONError$Outbound;
}
