/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DwollaError } from "./dwollaerror.js";

export type MaximumNumberOfResourcesSchemaErrorData = {
  code: string;
  message: string;
};

export class MaximumNumberOfResourcesSchemaError extends DwollaError {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: MaximumNumberOfResourcesSchemaErrorData;

  constructor(
    err: MaximumNumberOfResourcesSchemaErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "MaximumNumberOfResourcesSchemaError";
  }
}

/** @internal */
export const MaximumNumberOfResourcesSchemaError$inboundSchema: z.ZodType<
  MaximumNumberOfResourcesSchemaError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new MaximumNumberOfResourcesSchemaError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type MaximumNumberOfResourcesSchemaError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const MaximumNumberOfResourcesSchemaError$outboundSchema: z.ZodType<
  MaximumNumberOfResourcesSchemaError$Outbound,
  z.ZodTypeDef,
  MaximumNumberOfResourcesSchemaError
> = z.instanceof(MaximumNumberOfResourcesSchemaError)
  .transform(v => v.data$)
  .pipe(z.object({
    code: z.string(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MaximumNumberOfResourcesSchemaError$ {
  /** @deprecated use `MaximumNumberOfResourcesSchemaError$inboundSchema` instead. */
  export const inboundSchema =
    MaximumNumberOfResourcesSchemaError$inboundSchema;
  /** @deprecated use `MaximumNumberOfResourcesSchemaError$outboundSchema` instead. */
  export const outboundSchema =
    MaximumNumberOfResourcesSchemaError$outboundSchema;
  /** @deprecated use `MaximumNumberOfResourcesSchemaError$Outbound` instead. */
  export type Outbound = MaximumNumberOfResourcesSchemaError$Outbound;
}
