/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DwollaError } from "./dwollaerror.js";

export type OperationBlockedErrorData = {
  code: string;
  message: string;
  embedded?: models.OperationBlockedErrorEmbedded | undefined;
};

export class OperationBlockedError extends DwollaError {
  code: string;
  embedded?: models.OperationBlockedErrorEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: OperationBlockedErrorData;

  constructor(
    err: OperationBlockedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "OperationBlockedError";
  }
}

/** @internal */
export const OperationBlockedError$inboundSchema: z.ZodType<
  OperationBlockedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() => models.OperationBlockedErrorEmbedded$inboundSchema)
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new OperationBlockedError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type OperationBlockedError$Outbound = {
  code: string;
  message: string;
  _embedded?: models.OperationBlockedErrorEmbedded$Outbound | undefined;
};

/** @internal */
export const OperationBlockedError$outboundSchema: z.ZodType<
  OperationBlockedError$Outbound,
  z.ZodTypeDef,
  OperationBlockedError
> = z.instanceof(OperationBlockedError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      code: z.string(),
      message: z.string(),
      embedded: z.lazy(() =>
        models.OperationBlockedErrorEmbedded$outboundSchema
      ).optional(),
    }).transform((v) => {
      return remap$(v, {
        embedded: "_embedded",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OperationBlockedError$ {
  /** @deprecated use `OperationBlockedError$inboundSchema` instead. */
  export const inboundSchema = OperationBlockedError$inboundSchema;
  /** @deprecated use `OperationBlockedError$outboundSchema` instead. */
  export const outboundSchema = OperationBlockedError$outboundSchema;
  /** @deprecated use `OperationBlockedError$Outbound` instead. */
  export type Outbound = OperationBlockedError$Outbound;
}
