/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DwollaError } from "./dwollaerror.js";

export type PrefundingSourceNotAllowedErrorData = {
  code: string;
  message: string;
  embedded?: models.PrefundingSourceNotAllowedErrorEmbedded | undefined;
};

export class PrefundingSourceNotAllowedError extends DwollaError {
  code: string;
  embedded?: models.PrefundingSourceNotAllowedErrorEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: PrefundingSourceNotAllowedErrorData;

  constructor(
    err: PrefundingSourceNotAllowedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "PrefundingSourceNotAllowedError";
  }
}

/** @internal */
export const PrefundingSourceNotAllowedError$inboundSchema: z.ZodType<
  PrefundingSourceNotAllowedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() =>
    models.PrefundingSourceNotAllowedErrorEmbedded$inboundSchema
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new PrefundingSourceNotAllowedError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
