/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type RtpUnverifiedSenderNotSupportedErrorData = {
  code: string;
  message: string;
  embedded?: models.RtpUnverifiedSenderNotSupportedErrorEmbedded | undefined;
};

export class RtpUnverifiedSenderNotSupportedError extends Error {
  code: string;
  embedded?: models.RtpUnverifiedSenderNotSupportedErrorEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: RtpUnverifiedSenderNotSupportedErrorData;

  constructor(err: RtpUnverifiedSenderNotSupportedErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "RtpUnverifiedSenderNotSupportedError";
  }
}

/** @internal */
export const RtpUnverifiedSenderNotSupportedError$inboundSchema: z.ZodType<
  RtpUnverifiedSenderNotSupportedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() =>
    models.RtpUnverifiedSenderNotSupportedErrorEmbedded$inboundSchema
  ).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new RtpUnverifiedSenderNotSupportedError(remapped);
  });

/** @internal */
export type RtpUnverifiedSenderNotSupportedError$Outbound = {
  code: string;
  message: string;
  _embedded?:
    | models.RtpUnverifiedSenderNotSupportedErrorEmbedded$Outbound
    | undefined;
};

/** @internal */
export const RtpUnverifiedSenderNotSupportedError$outboundSchema: z.ZodType<
  RtpUnverifiedSenderNotSupportedError$Outbound,
  z.ZodTypeDef,
  RtpUnverifiedSenderNotSupportedError
> = z.instanceof(RtpUnverifiedSenderNotSupportedError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      code: z.string(),
      message: z.string(),
      embedded: z.lazy(() =>
        models.RtpUnverifiedSenderNotSupportedErrorEmbedded$outboundSchema
      ).optional(),
    }).transform((v) => {
      return remap$(v, {
        embedded: "_embedded",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RtpUnverifiedSenderNotSupportedError$ {
  /** @deprecated use `RtpUnverifiedSenderNotSupportedError$inboundSchema` instead. */
  export const inboundSchema =
    RtpUnverifiedSenderNotSupportedError$inboundSchema;
  /** @deprecated use `RtpUnverifiedSenderNotSupportedError$outboundSchema` instead. */
  export const outboundSchema =
    RtpUnverifiedSenderNotSupportedError$outboundSchema;
  /** @deprecated use `RtpUnverifiedSenderNotSupportedError$Outbound` instead. */
  export type Outbound = RtpUnverifiedSenderNotSupportedError$Outbound;
}
