/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type TransferExpiredForFeeErrorData = {
  code: string;
  message: string;
  embedded?: models.TransferExpiredForFeeErrorEmbedded | undefined;
};

export class TransferExpiredForFeeError extends Error {
  code: string;
  embedded?: models.TransferExpiredForFeeErrorEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: TransferExpiredForFeeErrorData;

  constructor(err: TransferExpiredForFeeErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "TransferExpiredForFeeError";
  }
}

/** @internal */
export const TransferExpiredForFeeError$inboundSchema: z.ZodType<
  TransferExpiredForFeeError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() =>
    models.TransferExpiredForFeeErrorEmbedded$inboundSchema
  ).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new TransferExpiredForFeeError(remapped);
  });

/** @internal */
export type TransferExpiredForFeeError$Outbound = {
  code: string;
  message: string;
  _embedded?: models.TransferExpiredForFeeErrorEmbedded$Outbound | undefined;
};

/** @internal */
export const TransferExpiredForFeeError$outboundSchema: z.ZodType<
  TransferExpiredForFeeError$Outbound,
  z.ZodTypeDef,
  TransferExpiredForFeeError
> = z.instanceof(TransferExpiredForFeeError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      code: z.string(),
      message: z.string(),
      embedded: z.lazy(() =>
        models.TransferExpiredForFeeErrorEmbedded$outboundSchema
      ).optional(),
    }).transform((v) => {
      return remap$(v, {
        embedded: "_embedded",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransferExpiredForFeeError$ {
  /** @deprecated use `TransferExpiredForFeeError$inboundSchema` instead. */
  export const inboundSchema = TransferExpiredForFeeError$inboundSchema;
  /** @deprecated use `TransferExpiredForFeeError$outboundSchema` instead. */
  export const outboundSchema = TransferExpiredForFeeError$outboundSchema;
  /** @deprecated use `TransferExpiredForFeeError$Outbound` instead. */
  export type Outbound = TransferExpiredForFeeError$Outbound;
}
