/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";
import { DwollaError } from "./dwollaerror.js";

export type WireAccountRestrictedErrorData = {
  code: string;
  message: string;
  embedded?: models.WireAccountRestrictedErrorEmbedded | undefined;
};

export class WireAccountRestrictedError extends DwollaError {
  code: string;
  embedded?: models.WireAccountRestrictedErrorEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: WireAccountRestrictedErrorData;

  constructor(
    err: WireAccountRestrictedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "WireAccountRestrictedError";
  }
}

/** @internal */
export const WireAccountRestrictedError$inboundSchema: z.ZodType<
  WireAccountRestrictedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() =>
    models.WireAccountRestrictedErrorEmbedded$inboundSchema
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new WireAccountRestrictedError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type WireAccountRestrictedError$Outbound = {
  code: string;
  message: string;
  _embedded?: models.WireAccountRestrictedErrorEmbedded$Outbound | undefined;
};

/** @internal */
export const WireAccountRestrictedError$outboundSchema: z.ZodType<
  WireAccountRestrictedError$Outbound,
  z.ZodTypeDef,
  WireAccountRestrictedError
> = z.instanceof(WireAccountRestrictedError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      code: z.string(),
      message: z.string(),
      embedded: z.lazy(() =>
        models.WireAccountRestrictedErrorEmbedded$outboundSchema
      ).optional(),
    }).transform((v) => {
      return remap$(v, {
        embedded: "_embedded",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WireAccountRestrictedError$ {
  /** @deprecated use `WireAccountRestrictedError$inboundSchema` instead. */
  export const inboundSchema = WireAccountRestrictedError$inboundSchema;
  /** @deprecated use `WireAccountRestrictedError$outboundSchema` instead. */
  export const outboundSchema = WireAccountRestrictedError$outboundSchema;
  /** @deprecated use `WireAccountRestrictedError$Outbound` instead. */
  export type Outbound = WireAccountRestrictedError$Outbound;
}
