/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type WireNotEnabledErrorData = {
  code: string;
  message: string;
  embedded?: models.WireNotEnabledErrorEmbedded | undefined;
};

export class WireNotEnabledError extends Error {
  code: string;
  embedded?: models.WireNotEnabledErrorEmbedded | undefined;

  /** The original data that was passed to this error instance. */
  data$: WireNotEnabledErrorData;

  constructor(err: WireNotEnabledErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "WireNotEnabledError";
  }
}

/** @internal */
export const WireNotEnabledError$inboundSchema: z.ZodType<
  WireNotEnabledError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() => models.WireNotEnabledErrorEmbedded$inboundSchema)
    .optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new WireNotEnabledError(remapped);
  });

/** @internal */
export type WireNotEnabledError$Outbound = {
  code: string;
  message: string;
  _embedded?: models.WireNotEnabledErrorEmbedded$Outbound | undefined;
};

/** @internal */
export const WireNotEnabledError$outboundSchema: z.ZodType<
  WireNotEnabledError$Outbound,
  z.ZodTypeDef,
  WireNotEnabledError
> = z.instanceof(WireNotEnabledError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      code: z.string(),
      message: z.string(),
      embedded: z.lazy(() => models.WireNotEnabledErrorEmbedded$outboundSchema)
        .optional(),
    }).transform((v) => {
      return remap$(v, {
        embedded: "_embedded",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WireNotEnabledError$ {
  /** @deprecated use `WireNotEnabledError$inboundSchema` instead. */
  export const inboundSchema = WireNotEnabledError$inboundSchema;
  /** @deprecated use `WireNotEnabledError$outboundSchema` instead. */
  export const outboundSchema = WireNotEnabledError$outboundSchema;
  /** @deprecated use `WireNotEnabledError$Outbound` instead. */
  export type Outbound = WireNotEnabledError$Outbound;
}
