/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type WithdrawInvalidWireBeneficiaryRegionErrorData = {
  code: string;
  message: string;
  embedded?:
    | models.WithdrawInvalidWireBeneficiaryRegionErrorEmbedded
    | undefined;
};

export class WithdrawInvalidWireBeneficiaryRegionError extends Error {
  code: string;
  embedded?:
    | models.WithdrawInvalidWireBeneficiaryRegionErrorEmbedded
    | undefined;

  /** The original data that was passed to this error instance. */
  data$: WithdrawInvalidWireBeneficiaryRegionErrorData;

  constructor(err: WithdrawInvalidWireBeneficiaryRegionErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.embedded != null) this.embedded = err.embedded;

    this.name = "WithdrawInvalidWireBeneficiaryRegionError";
  }
}

/** @internal */
export const WithdrawInvalidWireBeneficiaryRegionError$inboundSchema: z.ZodType<
  WithdrawInvalidWireBeneficiaryRegionError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  _embedded: z.lazy(() =>
    models.WithdrawInvalidWireBeneficiaryRegionErrorEmbedded$inboundSchema
  ).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_embedded": "embedded",
    });

    return new WithdrawInvalidWireBeneficiaryRegionError(remapped);
  });

/** @internal */
export type WithdrawInvalidWireBeneficiaryRegionError$Outbound = {
  code: string;
  message: string;
  _embedded?:
    | models.WithdrawInvalidWireBeneficiaryRegionErrorEmbedded$Outbound
    | undefined;
};

/** @internal */
export const WithdrawInvalidWireBeneficiaryRegionError$outboundSchema:
  z.ZodType<
    WithdrawInvalidWireBeneficiaryRegionError$Outbound,
    z.ZodTypeDef,
    WithdrawInvalidWireBeneficiaryRegionError
  > = z.instanceof(WithdrawInvalidWireBeneficiaryRegionError)
    .transform(v => v.data$)
    .pipe(
      z.object({
        code: z.string(),
        message: z.string(),
        embedded: z.lazy(() =>
          models
            .WithdrawInvalidWireBeneficiaryRegionErrorEmbedded$outboundSchema
        ).optional(),
      }).transform((v) => {
        return remap$(v, {
          embedded: "_embedded",
        });
      }),
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WithdrawInvalidWireBeneficiaryRegionError$ {
  /** @deprecated use `WithdrawInvalidWireBeneficiaryRegionError$inboundSchema` instead. */
  export const inboundSchema =
    WithdrawInvalidWireBeneficiaryRegionError$inboundSchema;
  /** @deprecated use `WithdrawInvalidWireBeneficiaryRegionError$outboundSchema` instead. */
  export const outboundSchema =
    WithdrawInvalidWireBeneficiaryRegionError$outboundSchema;
  /** @deprecated use `WithdrawInvalidWireBeneficiaryRegionError$Outbound` instead. */
  export type Outbound = WithdrawInvalidWireBeneficiaryRegionError$Outbound;
}
