/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { beneficialOwnersCertifyOwnership } from "../../funcs/beneficialOwnersCertifyOwnership.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.CertifyBeneficialOwnershipForCustomerRequest$inboundSchema,
};

export const tool$beneficialOwnersCertifyOwnership: ToolDefinition<
  typeof args
> = {
  name: "beneficial-owners-certify-ownership",
  description: `Certify beneficial ownership status

certify beneficial ownership status`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await beneficialOwnersCertifyOwnership(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
