/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersListBusinessClassifications } from "../../funcs/customersListBusinessClassifications.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$customersListBusinessClassifications: ToolDefinition = {
  name: "customers-list-business-classifications",
  description: `List business classification

Retrieve an _embedded list of business classifications that contains an _embedded list of industry classifications.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await customersListBusinessClassifications(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
