/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersRetrieveBusinessClassification } from "../../funcs/customersRetrieveBusinessClassification.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RetrieveBusinessClassificationRequest$inboundSchema,
};

export const tool$customersRetrieveBusinessClassification: ToolDefinition<
  typeof args
> = {
  name: "customers-retrieve-business-classification",
  description: `Retrieve a business classification

Retrieve a business classification`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersRetrieveBusinessClassification(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
