/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersDocumentsCreate } from "../../funcs/customersDocumentsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCustomerDocumentRequest$inboundSchema,
};

export const tool$customersDocumentsCreate: ToolDefinition<typeof args> = {
  name: "customers-documents-create",
  description: `Create a document for customer

Create a document for customer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersDocumentsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
