/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exchangeSessionsCreateCustomerExchangeSession } from "../../funcs/exchangeSessionsCreateCustomerExchangeSession.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCustomerExchangeSessionRequest$inboundSchema,
};

export const tool$exchangeSessionsCreateCustomerExchangeSession: ToolDefinition<
  typeof args
> = {
  name: "exchange-sessions-create-customer-exchange-session",
  description: `Create customer exchange session

Create a new exchange session for a customer to initiate Instant Account Verification using Dwolla's trusted open banking partners.
Currently supported partners are Plaid, Visa, and MX.

The redirect-url is conditionally required:
- Required for Visa exchange sessions
- Required for Plaid exchange sessions on mobile platforms (Android/iOS)
- Not required for MX exchange sessions or Plaid web sessions
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await exchangeSessionsCreateCustomerExchangeSession(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
