/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { exchangesGet } from "../../funcs/exchangesGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetExchangeRequest$inboundSchema,
};

export const tool$exchangesGet: ToolDefinition<typeof args> = {
  name: "exchanges-get",
  description: `Retrieve exchange resource

Retrieve exchange resource`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await exchangesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
