/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fundingSourcesGetMicroDeposits } from "../../funcs/fundingSourcesGetMicroDeposits.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMicroDepositsRequest$inboundSchema,
};

export const tool$fundingSourcesGetMicroDeposits: ToolDefinition<typeof args> =
  {
    name: "funding-sources-get-micro-deposits",
    description: `Retrieve micro-deposits details

Retrieve micro-deposits details`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await fundingSourcesGetMicroDeposits(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
