/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labelsRemove } from "../../funcs/labelsRemove.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveLabelRequest$inboundSchema,
};

export const tool$labelsRemove: ToolDefinition<typeof args> = {
  name: "labels-remove",
  description: `Remove a label

Remove a label`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labelsRemove(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
