/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labelsCreateLedgerEntry } from "../../funcs/labelsCreateLedgerEntry.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateLabelLedgerEntryRequest$inboundSchema,
};

export const tool$labelsCreateLedgerEntry: ToolDefinition<typeof args> = {
  name: "labels-create-ledger-entry",
  description: `Create a label ledger entry

Create a new entry on a Label Ledger. The amount tied to a Label cannot go negative, therefore if the amount of the label ledger entry exceeds the current amount tied to a Label then a validation error will be returned.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labelsCreateLedgerEntry(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
