/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { massPaymentsListItems } from "../../funcs/massPaymentsListItems.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListMassPaymentItemsRequest$inboundSchema,
};

export const tool$massPaymentsListItems: ToolDefinition<typeof args> = {
  name: "mass-payments-list-items",
  description: `List items for a mass payment

List items for a mass payment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await massPaymentsListItems(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
