/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { massPaymentsGet } from "../../funcs/massPaymentsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMassPaymentRequest$inboundSchema,
};

export const tool$massPaymentsGet: ToolDefinition<typeof args> = {
  name: "mass-payments-get",
  description: `Retrieve a mass payment

Retrieve a mass payment`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await massPaymentsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
