/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { massPaymentsGetMassPaymentItem } from "../../funcs/massPaymentsGetMassPaymentItem.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetMassPaymentItemRequest$inboundSchema,
};

export const tool$massPaymentsGetMassPaymentItem: ToolDefinition<typeof args> =
  {
    name: "mass-payments-get-mass-payment-item",
    description: `Retrieve mass payment item

Retrieve mass payment item`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await massPaymentsGetMassPaymentItem(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
