/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksRetryWebhook } from "../../funcs/webhooksRetryWebhook.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RetryWebhookRequest$inboundSchema,
};

export const tool$webhooksRetryWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-retry-webhook",
  description: `Retry a webhook

Retry a webhook`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksRetryWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
