/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { DwollaCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$accountCreateAccountFundingSource } from "./tools/accountCreateAccountFundingSource.js";
import { tool$accountGetAccount } from "./tools/accountGetAccount.js";
import { tool$accountListAccountFundingSources } from "./tools/accountListAccountFundingSources.js";
import { tool$accountListAccountMassPayments } from "./tools/accountListAccountMassPayments.js";
import { tool$accountListAndSearchAccountTransfers } from "./tools/accountListAndSearchAccountTransfers.js";
import { tool$beneficialOwnersCertifyBeneficialOwnershipForCustomer } from "./tools/beneficialOwnersCertifyBeneficialOwnershipForCustomer.js";
import { tool$beneficialOwnersCreateBeneficialOwnerForCustomer } from "./tools/beneficialOwnersCreateBeneficialOwnerForCustomer.js";
import { tool$beneficialOwnersDeleteBeneficialOwner } from "./tools/beneficialOwnersDeleteBeneficialOwner.js";
import { tool$beneficialOwnersGetBeneficialOwnershipStatusForCustomer } from "./tools/beneficialOwnersGetBeneficialOwnershipStatusForCustomer.js";
import { tool$beneficialOwnersListBeneficialOwnersForCustomer } from "./tools/beneficialOwnersListBeneficialOwnersForCustomer.js";
import { tool$beneficialOwnersRetrieveBeneficialOwner } from "./tools/beneficialOwnersRetrieveBeneficialOwner.js";
import { tool$beneficialOwnersUpdateBeneficialOwner } from "./tools/beneficialOwnersUpdateBeneficialOwner.js";
import { tool$customersCreateCustomer } from "./tools/customersCreateCustomer.js";
import { tool$customersGetCustomer } from "./tools/customersGetCustomer.js";
import { tool$customersListAndSearchCustomers } from "./tools/customersListAndSearchCustomers.js";
import { tool$customersListBusinessClassifications } from "./tools/customersListBusinessClassifications.js";
import { tool$customersRetrieveBusinessClassification } from "./tools/customersRetrieveBusinessClassification.js";
import { tool$customersUpdate } from "./tools/customersUpdate.js";
import { tool$documentsCreateBeneficialOwnerDocument } from "./tools/documentsCreateBeneficialOwnerDocument.js";
import { tool$documentsCreateCustomerDocument } from "./tools/documentsCreateCustomerDocument.js";
import { tool$documentsGetDocument } from "./tools/documentsGetDocument.js";
import { tool$documentsListBeneficialOwnerDocuments } from "./tools/documentsListBeneficialOwnerDocuments.js";
import { tool$documentsListCustomerDocuments } from "./tools/documentsListCustomerDocuments.js";
import { tool$eventsGetEvent } from "./tools/eventsGetEvent.js";
import { tool$exchangesCreateAccountExchange } from "./tools/exchangesCreateAccountExchange.js";
import { tool$exchangesCreateCustomerExchange } from "./tools/exchangesCreateCustomerExchange.js";
import { tool$exchangeSessionsCreateCustomerExchangeSession } from "./tools/exchangeSessionsCreateCustomerExchangeSession.js";
import { tool$exchangeSessionsCreateReAuthExchangeSession } from "./tools/exchangeSessionsCreateReAuthExchangeSession.js";
import { tool$exchangeSessionsListAvailableExchangeConnections } from "./tools/exchangeSessionsListAvailableExchangeConnections.js";
import { tool$exchangeSessionsRetrieveCustomerExchangeSession } from "./tools/exchangeSessionsRetrieveCustomerExchangeSession.js";
import { tool$exchangesGetExchange } from "./tools/exchangesGetExchange.js";
import { tool$exchangesGetExchangePartner } from "./tools/exchangesGetExchangePartner.js";
import { tool$exchangesListAccountExchanges } from "./tools/exchangesListAccountExchanges.js";
import { tool$exchangesListCustomerExchanges } from "./tools/exchangesListCustomerExchanges.js";
import { tool$exchangesListExchangePartners } from "./tools/exchangesListExchangePartners.js";
import { tool$fundingSourcesCreateCustomerFundingSource } from "./tools/fundingSourcesCreateCustomerFundingSource.js";
import { tool$fundingSourcesCreateCustomerFundingSourceToken } from "./tools/fundingSourcesCreateCustomerFundingSourceToken.js";
import { tool$fundingSourcesCreateCustomerIavToken } from "./tools/fundingSourcesCreateCustomerIavToken.js";
import { tool$fundingSourcesGetFundingSource } from "./tools/fundingSourcesGetFundingSource.js";
import { tool$fundingSourcesGetFundingSourceBalance } from "./tools/fundingSourcesGetFundingSourceBalance.js";
import { tool$fundingSourcesGetMicroDeposits } from "./tools/fundingSourcesGetMicroDeposits.js";
import { tool$fundingSourcesGetVanAchRouting } from "./tools/fundingSourcesGetVanAchRouting.js";
import { tool$fundingSourcesInitiateOrVerifyMicroDeposits } from "./tools/fundingSourcesInitiateOrVerifyMicroDeposits.js";
import { tool$fundingSourcesListCustomerFundingSources } from "./tools/fundingSourcesListCustomerFundingSources.js";
import { tool$fundingSourcesUpdateOrRemoveFundingSource } from "./tools/fundingSourcesUpdateOrRemoveFundingSource.js";
import { tool$kbaGetKbaQuestions } from "./tools/kbaGetKbaQuestions.js";
import { tool$kbaInitiateKbaForCustomer } from "./tools/kbaInitiateKbaForCustomer.js";
import { tool$kbaVerifyKbaQuestions } from "./tools/kbaVerifyKbaQuestions.js";
import { tool$labelsCreateCustomerLabel } from "./tools/labelsCreateCustomerLabel.js";
import { tool$labelsCreateLabelLedgerEntry } from "./tools/labelsCreateLabelLedgerEntry.js";
import { tool$labelsCreateLabelReallocation } from "./tools/labelsCreateLabelReallocation.js";
import { tool$labelsGetLabel } from "./tools/labelsGetLabel.js";
import { tool$labelsGetLabelLedgerEntry } from "./tools/labelsGetLabelLedgerEntry.js";
import { tool$labelsListCustomerLabels } from "./tools/labelsListCustomerLabels.js";
import { tool$labelsListLabelLedgerEntries } from "./tools/labelsListLabelLedgerEntries.js";
import { tool$labelsRemoveLabel } from "./tools/labelsRemoveLabel.js";
import { tool$labelsRetrieveLabelLedgerEntry } from "./tools/labelsRetrieveLabelLedgerEntry.js";
import { tool$massPaymentsGetMassPayment } from "./tools/massPaymentsGetMassPayment.js";
import { tool$massPaymentsGetMassPaymentItem } from "./tools/massPaymentsGetMassPaymentItem.js";
import { tool$massPaymentsInitiateMassPayment } from "./tools/massPaymentsInitiateMassPayment.js";
import { tool$massPaymentsListCustomerMassPayments } from "./tools/massPaymentsListCustomerMassPayments.js";
import { tool$massPaymentsListMassPaymentItems } from "./tools/massPaymentsListMassPaymentItems.js";
import { tool$massPaymentsUpdateMassPayment } from "./tools/massPaymentsUpdateMassPayment.js";
import { tool$rootRoot } from "./tools/rootRoot.js";
import { tool$transfersCancelTransfer } from "./tools/transfersCancelTransfer.js";
import { tool$transfersCreateOnDemandTransferAuthorization } from "./tools/transfersCreateOnDemandTransferAuthorization.js";
import { tool$transfersGetTransfer } from "./tools/transfersGetTransfer.js";
import { tool$transfersGetTransferFailureReason } from "./tools/transfersGetTransferFailureReason.js";
import { tool$transfersInitiateTransfer } from "./tools/transfersInitiateTransfer.js";
import { tool$transfersListCustomerTransfers } from "./tools/transfersListCustomerTransfers.js";
import { tool$transfersListTransferFees } from "./tools/transfersListTransferFees.js";
import { tool$webhooksGetWebhook } from "./tools/webhooksGetWebhook.js";
import { tool$webhooksListWebhookRetries } from "./tools/webhooksListWebhookRetries.js";
import { tool$webhooksRetryWebhook } from "./tools/webhooksRetryWebhook.js";
import { tool$webhookSubscriptionsCreateWebhookSubscription } from "./tools/webhookSubscriptionsCreateWebhookSubscription.js";
import { tool$webhookSubscriptionsDelete } from "./tools/webhookSubscriptionsDelete.js";
import { tool$webhookSubscriptionsGetWebhookSubscription } from "./tools/webhookSubscriptionsGetWebhookSubscription.js";
import { tool$webhookSubscriptionsListWebhooks } from "./tools/webhookSubscriptionsListWebhooks.js";
import { tool$webhookSubscriptionsListWebhookSubscriptions } from "./tools/webhookSubscriptionsListWebhookSubscriptions.js";
import { tool$webhookSubscriptionsUpdateWebhookSubscription } from "./tools/webhookSubscriptionsUpdateWebhookSubscription.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  bearerAuth?: SDKOptions["bearerAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Dwolla",
    version: "0.0.1",
  });

  const client = new DwollaCore({
    bearerAuth: deps.bearerAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$rootRoot);
  tool(tool$accountGetAccount);
  tool(tool$accountCreateAccountFundingSource);
  tool(tool$accountListAccountFundingSources);
  tool(tool$accountListAndSearchAccountTransfers);
  tool(tool$accountListAccountMassPayments);
  tool(tool$customersListAndSearchCustomers);
  tool(tool$customersCreateCustomer);
  tool(tool$customersGetCustomer);
  tool(tool$customersUpdate);
  tool(tool$customersListBusinessClassifications);
  tool(tool$customersRetrieveBusinessClassification);
  tool(tool$beneficialOwnersListBeneficialOwnersForCustomer);
  tool(tool$beneficialOwnersCreateBeneficialOwnerForCustomer);
  tool(tool$beneficialOwnersRetrieveBeneficialOwner);
  tool(tool$beneficialOwnersUpdateBeneficialOwner);
  tool(tool$beneficialOwnersDeleteBeneficialOwner);
  tool(tool$beneficialOwnersGetBeneficialOwnershipStatusForCustomer);
  tool(tool$beneficialOwnersCertifyBeneficialOwnershipForCustomer);
  tool(tool$documentsListCustomerDocuments);
  tool(tool$documentsCreateCustomerDocument);
  tool(tool$documentsListBeneficialOwnerDocuments);
  tool(tool$documentsCreateBeneficialOwnerDocument);
  tool(tool$documentsGetDocument);
  tool(tool$kbaInitiateKbaForCustomer);
  tool(tool$kbaGetKbaQuestions);
  tool(tool$kbaVerifyKbaQuestions);
  tool(tool$fundingSourcesListCustomerFundingSources);
  tool(tool$fundingSourcesCreateCustomerFundingSource);
  tool(tool$fundingSourcesCreateCustomerFundingSourceToken);
  tool(tool$fundingSourcesCreateCustomerIavToken);
  tool(tool$fundingSourcesGetFundingSource);
  tool(tool$fundingSourcesUpdateOrRemoveFundingSource);
  tool(tool$fundingSourcesGetMicroDeposits);
  tool(tool$fundingSourcesInitiateOrVerifyMicroDeposits);
  tool(tool$fundingSourcesGetFundingSourceBalance);
  tool(tool$fundingSourcesGetVanAchRouting);
  tool(tool$transfersInitiateTransfer);
  tool(tool$transfersGetTransfer);
  tool(tool$transfersCancelTransfer);
  tool(tool$transfersListCustomerTransfers);
  tool(tool$transfersListTransferFees);
  tool(tool$transfersGetTransferFailureReason);
  tool(tool$transfersCreateOnDemandTransferAuthorization);
  tool(tool$massPaymentsInitiateMassPayment);
  tool(tool$massPaymentsGetMassPayment);
  tool(tool$massPaymentsUpdateMassPayment);
  tool(tool$massPaymentsListMassPaymentItems);
  tool(tool$massPaymentsGetMassPaymentItem);
  tool(tool$massPaymentsListCustomerMassPayments);
  tool(tool$labelsGetLabel);
  tool(tool$labelsRemoveLabel);
  tool(tool$labelsListCustomerLabels);
  tool(tool$labelsCreateCustomerLabel);
  tool(tool$labelsListLabelLedgerEntries);
  tool(tool$labelsCreateLabelLedgerEntry);
  tool(tool$labelsGetLabelLedgerEntry);
  tool(tool$labelsCreateLabelReallocation);
  tool(tool$labelsRetrieveLabelLedgerEntry);
  tool(tool$eventsGetEvent);
  tool(tool$webhookSubscriptionsListWebhookSubscriptions);
  tool(tool$webhookSubscriptionsCreateWebhookSubscription);
  tool(tool$webhookSubscriptionsGetWebhookSubscription);
  tool(tool$webhookSubscriptionsUpdateWebhookSubscription);
  tool(tool$webhookSubscriptionsDelete);
  tool(tool$webhookSubscriptionsListWebhooks);
  tool(tool$webhooksGetWebhook);
  tool(tool$webhooksListWebhookRetries);
  tool(tool$webhooksRetryWebhook);
  tool(tool$exchangesListExchangePartners);
  tool(tool$exchangesGetExchangePartner);
  tool(tool$exchangesListAccountExchanges);
  tool(tool$exchangesCreateAccountExchange);
  tool(tool$exchangesGetExchange);
  tool(tool$exchangesListCustomerExchanges);
  tool(tool$exchangesCreateCustomerExchange);
  tool(tool$exchangeSessionsCreateCustomerExchangeSession);
  tool(tool$exchangeSessionsRetrieveCustomerExchangeSession);
  tool(tool$exchangeSessionsCreateReAuthExchangeSession);
  tool(tool$exchangeSessionsListAvailableExchangeConnections);

  return server;
}
