/*
 * Code originally generated by Speakeasy (https://www.speakeasy.com).
 */

import { expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Accounts Exchanges List Account Exchanges", async () => {
  const testHttpClient = createTestHTTPClient("listAccountExchanges");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.accounts.exchanges.list();
  expect(result).toBeDefined();
  // Assert structure rather than exact payload to tolerate real sandbox data
  expect(result.links).toBeDefined();
  expect(result.embedded).toBeDefined();
  expect(Array.isArray(result.embedded?.exchanges ?? [])).toBe(true);
  expect(typeof result.total).toBe("number");

  if ((result.embedded?.exchanges?.length ?? 0) > 0) {
    const firstExchange = result.embedded!.exchanges![0]!;
    expect(firstExchange.id).toBeDefined();
    expect(firstExchange.status).toBeDefined();
    expect(firstExchange.created).toBeInstanceOf(Date);
    expect(firstExchange.links).toBeDefined();
  }
});

test.skip("Accounts Exchanges Create Account Exchange", async () => {
  // Skipped: This test requires a valid Plaid processor token which expires quickly.
  // The endpoint returns 201 with Location header and no body on success.
  const testHttpClient = createTestHTTPClient("createAccountExchange");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.accounts.exchanges.create({
    links: {
      exchangePartner: {
        href:
            "https://api-sandbox.dwolla.com/exchange-partners/3aef60d1-878f-4692-8c06-c6b478efb60d",
      },
    },
    token: "processor-sandbox-add4b58b-902c-4810-b6cd-d58dda4e0fe3",
  });
  
  // Create exchange returns 201 with Location header, extract the exchange ID
  const locationHeader =
    result?.headers["Location"]?.[0] ?? result?.headers["location"]?.[0];
  expect(locationHeader).toBeDefined();
});
