/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Accounts Masspayments List Mass Payments", async () => {
  const testHttpClient = createTestHTTPClient("listMassPayments");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.accounts.massPayments.list({
    id: "5e7cd80f-3a4a-451e-9cd6-a86fc571741f",
  });
  expect(result).toBeDefined();
  // Assert structure rather than exact payload to tolerate real sandbox data
  expect(result.links).toBeDefined();
  expect(result.embedded).toBeDefined();
  expect(Array.isArray(result.embedded?.massPayments ?? [])).toBe(true);
  expect(typeof result.total).toBe("number");

  if ((result.embedded?.massPayments?.length ?? 0) > 0) {
    const firstMp = result.embedded!.massPayments![0]!;
    expect(firstMp.id).toBeDefined();
    expect(firstMp.status).toBeDefined();
    expect(firstMp.created).toBeInstanceOf(Date);
    expect(firstMp.total).toBeDefined();
    expect(firstMp.total?.value).toBeDefined();
    expect(firstMp.total?.currency).toBeDefined();
    expect(firstMp.links).toBeDefined();
  }
});
