/*
 * Code originally generated by Speakeasy (https://www.speakeasy.com).
 */

import { beforeAll, expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createDwollaClient } from "./setup.js";

let dwolla: Dwolla;

beforeAll(async () => {
  dwolla = createDwollaClient("customersexchanges");
}, 30000); // 30 second timeout for setup initialization

// Skipped: This test requires a Open Banking which is behind a feature flag that requires a manual approval from Dwolla
test.skip("Customers Exchanges List Customer Exchanges", async () => {
  const result = await dwolla.customers.exchanges.list({
    id: "customerId",
  });
  expect(result).toBeDefined();

  // Assert structure rather than exact payload to tolerate real sandbox data
  expect(result.links).toBeDefined();
  expect(result.links?.["self"]).toBeDefined();
  expect(result.embedded).toBeDefined();
  expect(Array.isArray(result.embedded?.exchanges ?? [])).toBe(true);
  expect(typeof result.total).toBe("number");

  // Validate shape of the first exchange if present
  if ((result.embedded?.exchanges?.length ?? 0) > 0) {
    const first = result.embedded!.exchanges![0]!;
    expect(first.id).toBeDefined();
    expect(first.status).toBeDefined();
    expect(first.created).toBeInstanceOf(Date);
    expect(first.links).toBeDefined();
    expect(first.links?.["self"]).toBeDefined();
    expect(first.links?.["customer"]).toBeDefined();
    expect(first.links?.["exchange-partner"]).toBeDefined();
  }
});

// Skipped: This test requires a Open Banking which is behind a feature flag that requires a manual approval from Dwolla
test.skip("Customers List Available Exchange Connections", async () => {
  const result = await dwolla.customers.listAvailableConnections({
    id: "customerId",
  });
  expect(result).toBeDefined();
  expect(result.links).toBeDefined();
  expect(result.links.self).toBeDefined();
  expect(result.links.customers).toBeDefined();
  expect(result.embedded).toBeDefined();
  expect(
    Array.isArray(result.embedded?.availableExchangeConnections ?? []),
  ).toBe(true);
});
