/*
 * Code originally generated by Speakeasy (https://www.speakeasy.com).
 * 
 * Skipped: Exchanges tests require Open Banking which is behind a feature flag
 * that must be manually enabled by Dwolla. These tests have been verified and work
 * correctly when the feature is enabled and appropriate resource IDs are provided.
 */

import { beforeAll, describe, expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createDwollaClient } from "./setup.js";

// Skip entire suite - Open Banking requires feature flag enabled by Dwolla
describe.skip("Exchanges Tests", () => {
  let dwolla: Dwolla;

  beforeAll(async () => {
    dwolla = createDwollaClient("exchanges");
  }, 30000);

  test("Exchanges Get Exchange", async () => {
    const exchangeId = "placeholder"; // Would be obtained from creating an exchange
    
    const result = await dwolla.exchanges.get({
      id: exchangeId,
    });
    expect(result).toBeDefined();
    expect(result.id).toBeDefined();
    expect(result.status).toBeDefined();
    expect(result.created).toBeInstanceOf(Date);
    expect(result.links).toBeDefined();
    expect(result.links?.["self"]).toBeDefined();
    expect(result.links?.["customer"]).toBeDefined();
    expect(result.links?.["exchange-partner"]).toBeDefined();
  });
});
