/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Items List Mass Payment Items", async () => {
  const testHttpClient = createTestHTTPClient("listMassPaymentItems");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.massPayments.items.list({
    id: "9061743f-7cd4-48d7-94db-b3a700fab810",
  });
  expect(result).toBeDefined();
  // Assert structure rather than exact payload
  expect(result.links).toBeDefined();
  expect(result.links?.self).toBeDefined();
  expect(result.embedded).toBeDefined();
  expect(Array.isArray(result.embedded?.items ?? [])).toBe(true);
  expect(typeof result.total).toBe("number");

  // Validate shape of the first item if present
  if ((result.embedded?.items?.length ?? 0) > 0) {
    const first = result.embedded!.items![0]!;
    expect(first.id).toBeDefined();
    expect(first.status).toBeDefined();
    expect(first.amount).toBeDefined();
    expect(first.amount?.value).toBeDefined();
    expect(first.amount?.currency).toBeDefined();
    expect(first.links).toBeDefined();
    expect(first.links?.self).toBeDefined();
    expect(first.links?.massPayment).toBeDefined();
    expect(first.links?.destination).toBeDefined();
    
    // Optional fields
    if (first.metadata) {
      expect(typeof first.metadata).toBe("object");
    }
    if (first.processingChannel) {
      expect(typeof first.processingChannel).toBe("object");
    }
  }
});

test("Items Get Mass Payment Item", async () => {
  const testHttpClient = createTestHTTPClient("getMassPaymentItem");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.massPayments.items.get({
    itemId: "233d76b2-26f8-4b73-b7fe-5f8d94d0bdb3",
  });
  expect(result).toBeDefined();
  // Assert structure rather than exact payload
  expect(result.id).toBeDefined();
  expect(result.status).toBeDefined();
  expect(result.amount).toBeDefined();
  expect(result.amount?.value).toBeDefined();
  expect(result.amount?.currency).toBeDefined();
  expect(result.links).toBeDefined();
  expect(result.links?.self).toBeDefined();
  expect(result.links?.massPayment).toBeDefined();
  expect(result.links?.destination).toBeDefined();
  
  // Optional fields
  if (result.metadata) {
    expect(typeof result.metadata).toBe("object");
  }
  if (result.processingChannel) {
    expect(typeof result.processingChannel).toBe("object");
  }
});
