/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Masspayments Get Mass Payment", async () => {
  const testHttpClient = createTestHTTPClient("getMassPayment");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.massPayments.get({
    id: "9061743f-7cd4-48d7-94db-b3a700fab810",
  });
  expect(result).toBeDefined();
  // Assert structure rather than exact payload
  expect(result.id).toBeDefined();
  expect(result.status).toBeDefined();
  expect(result.created).toBeInstanceOf(Date);
  expect(result.links).toBeDefined();
  expect(result.total).toBeDefined();
  expect(result.total?.value).toBeDefined();
  expect(result.total?.currency).toBeDefined();
  
  // Optional fields
  if (result.totalFees) {
    expect(result.totalFees.value).toBeDefined();
    expect(result.totalFees.currency).toBeDefined();
  }
  if (result.correlationId) {
    expect(typeof result.correlationId).toBe("string");
  }
});

test("Masspayments Update Mass Payment", async () => {
  const testHttpClient = createTestHTTPClient("updateMassPayment");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.massPayments.update({
    id: "9061743f-7cd4-48d7-94db-b3a700fab810",
    requestBody: {
      status: "cancelled",
    },
  });
  expect(result).toBeDefined();
  // Assert structure rather than exact payload
  expect(result.id).toBeDefined();
  expect(result.status).toBeDefined();
  expect(result.created).toBeInstanceOf(Date);
  expect(result.links).toBeDefined();
  expect(result.total).toBeDefined();
  expect(result.total?.value).toBeDefined();
  expect(result.total?.currency).toBeDefined();
  
  // Optional fields
  if (result.totalFees) {
    expect(result.totalFees.value).toBeDefined();
    expect(result.totalFees.currency).toBeDefined();
  }
  if (result.correlationId) {
    expect(typeof result.correlationId).toBe("string");
  }
});
