/*
 * Code originally generated by Speakeasy (https://www.speakeasy.com).
 */

import { expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Retries List Webhook Retries", async () => {
  const testHttpClient = createTestHTTPClient("listWebhookRetries");

  const dwolla = new Dwolla({
    serverURL: "https://api-sandbox.dwolla.com",
    httpClient: testHttpClient,
    security: {
      clientID: process.env["DWOLLA_CLIENT_ID"] ?? "value",
      clientSecret: process.env["DWOLLA_CLIENT_SECRET"] ?? "value",
    },
  });

  const result = await dwolla.webhooks.retries.list({
    id: "b9fa8254-3427-4a07-ab36-b7a76504b614",
  });
  expect(result).toBeDefined();
  // Assert structure rather than exact payload to tolerate real sandbox data
  expect(result.links).toBeDefined();
  expect(result.links?.self).toBeDefined();
  expect(result.embedded).toBeDefined();
  expect(Array.isArray(result.embedded?.retries ?? [])).toBe(true);
  expect(typeof result.total).toBe("number");

  // Validate shape of the first retry if present
  if ((result.embedded?.retries?.length ?? 0) > 0) {
    const first = result.embedded!.retries![0]!;
    expect(first.id).toBeDefined();
    expect(first.timestamp).toBeInstanceOf(Date);
    expect(first.links).toBeDefined();
    expect(first.links?.self).toBeDefined();
    expect(first.links?.webhook).toBeDefined();
  }
});
