/*
 * Code originally generated by Speakeasy (https://www.speakeasy.com).
 * Consolidated transfer tests - covers transfers, fees, and failure reasons.
 * Creates a single business customer and uses it for all transfer tests.
 */

import { beforeAll, expect, test } from "vitest";
import { Dwolla } from "../index.js";
import { createDwollaClient, createPersonalCustomer, createBankFundingSource, createVerifiedBankFundingSource, extractIdFromLocationHeader, createUnverifiedCustomer } from "./setup.js";

let dwolla: Dwolla;
let bankFsId: string | undefined;
let destinationBankFsId: string | undefined;
let transferWithFeeId: string | undefined;
let transferToCancelId: string | undefined;

beforeAll(async () => {
  dwolla = createDwollaClient("transfers");
  
  // Create a business customer with a verified bank funding source (for transfers)
  const customerId = await createPersonalCustomer(dwolla);
  // Use verified bank for source (needs microdeposit verification to send)
  bankFsId = await createVerifiedBankFundingSource(dwolla, customerId, "Test Checking");

  // Create unverified customer as destination (doesn't need verification to receive)
  const receiverId = await createUnverifiedCustomer(dwolla);
  destinationBankFsId = await createBankFundingSource(dwolla, receiverId, "R03");
  
  // Create a transfer with fee for test
  // try {
    const transferResult = await dwolla.transfers.create({
      requestBody: {
        links: {
          source: {
            href: `https://api-sandbox.dwolla.com/funding-sources/${bankFsId}`,
          },
          destination: {
            href: `https://api-sandbox.dwolla.com/funding-sources/${destinationBankFsId}`,
          },
        },
        amount: {
          currency: "USD",
          value: "5.00",
        },
        fees: [
          {
            links: {
              chargeTo: {
                href: `https://api-sandbox.dwolla.com/customers/${customerId}`,
              },
            },
            amount: {
              currency: "USD",
              value: "0.50",
            },
          },
        ],
      },
    });
    transferWithFeeId = extractIdFromLocationHeader(transferResult?.headers);

    // In sandbox, simulate bank transfer processing to complete the transfer immediately
    if (transferWithFeeId) {
      await dwolla.sandboxSimulations.simulate();
    }

    // Create a transfer to cancel for test
    const transferToCancelResult = await dwolla.transfers.create({
      requestBody: {
        links: {
          source: {
            href: `https://api-sandbox.dwolla.com/funding-sources/${bankFsId}`,
          },
          destination: {
            href: `https://api-sandbox.dwolla.com/funding-sources/${destinationBankFsId}`,
          },
        },
        amount: {
          currency: "USD",
          value: "5.00",
        },
      },
    });
    transferToCancelId = extractIdFromLocationHeader(transferToCancelResult?.headers);

}, 30000);

// ============================================================================
// TRANSFERS TESTS
// ============================================================================

test("Transfers Get Transfer", async () => {
  const result = await dwolla.transfers.get({
    id: transferWithFeeId!,
  });
  expect(result).toBeDefined();
  expect(result.id).toBeDefined();
  expect(result.status).toBeDefined();
  expect(result.created).toBeInstanceOf(Date);
  expect(result.amount).toBeDefined();
  expect(result.amount?.value).toBeDefined();
  expect(result.amount?.currency).toBeDefined();
  expect(result.links).toBeDefined();
  expect(result.links?.["self"]).toBeDefined();
  expect(result.links?.["source"]).toBeDefined();
  expect(result.links?.["destination"]).toBeDefined();
  
  if (result.clearing) {
    expect(result.clearing.source).toBeDefined();
  }
  if (result.correlationId) {
    expect(typeof result.correlationId).toBe("string");
  }
  if (result.metadata) {
    expect(typeof result.metadata).toBe("object");
  }
  if (result.achDetails) {
    expect(typeof result.achDetails).toBe("object");
  }
  if (result.rtpDetails) {
    expect(typeof result.rtpDetails).toBe("object");
  }
  if (result.fedNowDetails) {
    expect(typeof result.fedNowDetails).toBe("object");
  }
  if (result.processingChannel) {
    expect(typeof result.processingChannel).toBe("object");
  }
});

test("Transfers Cancel Transfer", async () => {
  const result = await dwolla.transfers.cancel({
    id: transferToCancelId!,
    requestBody: {
      status: "cancelled",
    },
  });
  expect(result).toBeDefined();
});

// ============================================================================
// TRANSFER FEES TESTS
// ============================================================================

test("Transfers List Transfer Fees", async () => {
  const result = await dwolla.transfers.fees.list({
    id: transferWithFeeId!,
  });
  expect(result).toBeDefined();
  expect(Array.isArray(result.transactions ?? [])).toBe(true);
  expect(result.total).toBeDefined();
  
  if ((result.transactions?.length ?? 0) > 0) {
    const first = result.transactions![0]!;
    expect(first.id).toBeDefined();
    expect(first.status).toBeDefined();
    expect(first.amount).toBeDefined();
    expect(first.amount?.value).toBeDefined();
    expect(first.amount?.currency).toBeDefined();
    expect(first.created).toBeInstanceOf(Date);
    expect(first.links).toBeDefined();
  }
});

// ============================================================================
// TRANSFER FAILURE TESTS
// ============================================================================

test("Transfers Get Transfer Failure Reason", async () => {
  await dwolla.sandboxSimulations.simulate();
  
  const result = await dwolla.transfers.failure.get({
    id: transferWithFeeId!,
  });
  expect(result).toBeDefined();
  expect(result.code).toBeDefined();
  expect(result.description).toBeDefined();
  expect(result.links).toBeDefined();
  
  if (result.explanation) {
    expect(typeof result.explanation).toBe("string");
  }
});

