/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsGet } from "../funcs/accountsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { AccountsExchanges } from "./accountsexchanges.js";
import { AccountsFundingSources } from "./accountsfundingsources.js";
import { AccountsMassPayments } from "./accountsmasspayments.js";
import { AccountsTransfers } from "./accountstransfers.js";

export class Accounts extends ClientSDK {
  private _fundingSources?: AccountsFundingSources;
  get fundingSources(): AccountsFundingSources {
    return (this._fundingSources ??= new AccountsFundingSources(this._options));
  }

  private _transfers?: AccountsTransfers;
  get transfers(): AccountsTransfers {
    return (this._transfers ??= new AccountsTransfers(this._options));
  }

  private _massPayments?: AccountsMassPayments;
  get massPayments(): AccountsMassPayments {
    return (this._massPayments ??= new AccountsMassPayments(this._options));
  }

  private _exchanges?: AccountsExchanges;
  get exchanges(): AccountsExchanges {
    return (this._exchanges ??= new AccountsExchanges(this._options));
  }

  /**
   * Retrieve Account Details
   *
   * @remarks
   * Retrieve basic account details belonging to the authorized Dwolla account.
   */
  async get(
    request: operations.GetAccountRequest,
    options?: RequestOptions,
  ): Promise<models.Account> {
    return unwrapAsync(accountsGet(
      this,
      request,
      options,
    ));
  }
}
