/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsFundingSourcesCreate } from "../funcs/accountsFundingSourcesCreate.js";
import { accountsFundingSourcesList } from "../funcs/accountsFundingSourcesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AccountsFundingSources extends ClientSDK {
  /**
   * Create a funding source for an account
   *
   * @remarks
   * Create a funding source by adding a bank account to a Main Dwolla Account. This endpoint allows you to connect a checking or savings account using either manual bank account details or an exchange resource.
   *
   * For more information about funding sources, see the [Funding Sources API Reference](https://developers.dwolla.com/docs/api-reference/funding-sources).
   */
  async create(
    request: models.CreateAccountFundingSource,
    options?: RequestOptions,
  ): Promise<operations.CreateFundingSourceResponse | undefined> {
    return unwrapAsync(accountsFundingSourcesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List funding sources for an account
   *
   * @remarks
   * Get a list of all funding sources associated with a specific Main Dwolla Account. This endpoint returns both bank accounts and balance funding sources, with detailed information about each funding source's status, type, and available processing channels.
   */
  async list(
    request: operations.ListFundingSourcesRequest,
    options?: RequestOptions,
  ): Promise<models.FundingSources> {
    return unwrapAsync(accountsFundingSourcesList(
      this,
      request,
      options,
    ));
  }
}
