/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { businessClassificationsGet } from "../funcs/businessClassificationsGet.js";
import { businessClassificationsList } from "../funcs/businessClassificationsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BusinessClassifications extends ClientSDK {
  /**
   * List business classifications
   *
   * @remarks
   * Returns a directory of business and industry classifications required for creating business verified customers. Each business classification contains multiple industry classifications. The industry classification ID must be provided in the businessClassification parameter during business customer creation for verification.
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.ListBusinessClassificationsResponse> {
    return unwrapAsync(businessClassificationsList(
      this,
      options,
    ));
  }

  /**
   * Retrieve a business classification
   *
   * @remarks
   * Returns a specific business classification with its embedded industry classifications. Use this endpoint to browse available industry options within a business category and obtain the industry classification ID required for the businessClassification parameter when creating business verified customers.
   */
  async get(
    request: operations.RetrieveBusinessClassificationRequest,
    options?: RequestOptions,
  ): Promise<models.BusinessClassification> {
    return unwrapAsync(businessClassificationsGet(
      this,
      request,
      options,
    ));
  }
}
