/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersBeneficialOwnersCreate } from "../funcs/customersBeneficialOwnersCreate.js";
import { customersBeneficialOwnersList } from "../funcs/customersBeneficialOwnersList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CustomersBeneficialOwners extends ClientSDK {
  /**
   * List customer beneficial owners
   *
   * @remarks
   * Returns all beneficial owners associated with a business verified customer. Beneficial owners are individuals who directly or indirectly own 25% or more of the company's equity. Includes personal information, verification status, and address details for each owner.
   */
  async list(
    request: operations.ListBeneficialOwnersForCustomerRequest,
    options?: RequestOptions,
  ): Promise<models.BeneficialOwners> {
    return unwrapAsync(customersBeneficialOwnersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create customer beneficial owner
   *
   * @remarks
   * Creates a new beneficial owner for a business verified customer. Beneficial owners are individuals who own 25% or more of the company's equity. Requires personal information, address, and SSN or passport for identity verification.
   */
  async create(
    request: operations.CreateBeneficialOwnerForCustomerRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateBeneficialOwnerForCustomerResponse | undefined> {
    return unwrapAsync(customersBeneficialOwnersCreate(
      this,
      request,
      options,
    ));
  }
}
