/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersDocumentsCreate } from "../funcs/customersDocumentsCreate.js";
import { customersDocumentsList } from "../funcs/customersDocumentsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CustomersDocuments extends ClientSDK {
  /**
   * List documents for customer
   *
   * @remarks
   * List documents for customer
   */
  async list(
    request: operations.ListCustomerDocumentsRequest,
    options?: RequestOptions,
  ): Promise<models.Documents> {
    return unwrapAsync(customersDocumentsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a document for customer
   *
   * @remarks
   * Create a document for customer
   */
  async create(
    request: operations.CreateCustomerDocumentRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCustomerDocumentResponse | undefined> {
    return unwrapAsync(customersDocumentsCreate(
      this,
      request,
      options,
    ));
  }
}
