/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokensCreateApplicationAccessToken } from "../funcs/tokensCreateApplicationAccessToken.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tokens extends ClientSDK {
  /**
   * Create an application access token
   *
   * @remarks
   * Generates an access token that contains permissions scoped to the application owner's Dwolla Client Account.
   */
  async createApplicationAccessToken(
    request: operations.CreateApplicationAccessTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateApplicationAccessTokenResponse> {
    return unwrapAsync(tokensCreateApplicationAccessToken(
      this,
      request,
      options,
    ));
  }
}
