/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the dwolla SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx tokensCreate.example.ts
 */

import { Dwolla } from "dwolla";

const dwolla = new Dwolla();

async function main() {
  const result = await dwolla.tokens.create({
    basicAuth: process.env["DWOLLA_BASIC_AUTH"] ?? "",
  }, {
    grantType: "client_credentials",
  });

  console.log(result);
}

main().catch(console.error);
