workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Dwolla API:
        inputs:
            - location: https://raw.githubusercontent.com/Dwolla/dwolla-openapi/refs/heads/main/openapi.yml
        overlays:
            - location: ./.speakeasy/overlay.yaml
        output: ./generated/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/dwolla/dwolla/dwolla-api
targets:
    dwolla:
        target: typescript
        source: Dwolla API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/dwolla/dwolla/dwolla-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: true
