/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type From = {
  href?: string | undefined;
};

export type To = {
  href?: string | undefined;
};

export type CreateLabelReallocationLinks = {
  from?: From | undefined;
  to?: To | undefined;
};

export type CreateLabelReallocationAmount = {
  currency?: string | undefined;
  value?: string | undefined;
};

/**
 * Parameters to create a label reallocation
 */
export type CreateLabelReallocationRequest = {
  links: CreateLabelReallocationLinks;
  amount: CreateLabelReallocationAmount;
};

export type CreateLabelReallocationResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type From$Outbound = {
  href?: string | undefined;
};

/** @internal */
export const From$outboundSchema: z.ZodType<From$Outbound, z.ZodTypeDef, From> =
  z.object({
    href: z.string().optional(),
  });

export function fromToJSON(from: From): string {
  return JSON.stringify(From$outboundSchema.parse(from));
}

/** @internal */
export type To$Outbound = {
  href?: string | undefined;
};

/** @internal */
export const To$outboundSchema: z.ZodType<To$Outbound, z.ZodTypeDef, To> = z
  .object({
    href: z.string().optional(),
  });

export function toToJSON(to: To): string {
  return JSON.stringify(To$outboundSchema.parse(to));
}

/** @internal */
export type CreateLabelReallocationLinks$Outbound = {
  from?: From$Outbound | undefined;
  to?: To$Outbound | undefined;
};

/** @internal */
export const CreateLabelReallocationLinks$outboundSchema: z.ZodType<
  CreateLabelReallocationLinks$Outbound,
  z.ZodTypeDef,
  CreateLabelReallocationLinks
> = z.object({
  from: z.lazy(() => From$outboundSchema).optional(),
  to: z.lazy(() => To$outboundSchema).optional(),
});

export function createLabelReallocationLinksToJSON(
  createLabelReallocationLinks: CreateLabelReallocationLinks,
): string {
  return JSON.stringify(
    CreateLabelReallocationLinks$outboundSchema.parse(
      createLabelReallocationLinks,
    ),
  );
}

/** @internal */
export type CreateLabelReallocationAmount$Outbound = {
  currency?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const CreateLabelReallocationAmount$outboundSchema: z.ZodType<
  CreateLabelReallocationAmount$Outbound,
  z.ZodTypeDef,
  CreateLabelReallocationAmount
> = z.object({
  currency: z.string().optional(),
  value: z.string().optional(),
});

export function createLabelReallocationAmountToJSON(
  createLabelReallocationAmount: CreateLabelReallocationAmount,
): string {
  return JSON.stringify(
    CreateLabelReallocationAmount$outboundSchema.parse(
      createLabelReallocationAmount,
    ),
  );
}

/** @internal */
export type CreateLabelReallocationRequest$Outbound = {
  _links: CreateLabelReallocationLinks$Outbound;
  amount: CreateLabelReallocationAmount$Outbound;
};

/** @internal */
export const CreateLabelReallocationRequest$outboundSchema: z.ZodType<
  CreateLabelReallocationRequest$Outbound,
  z.ZodTypeDef,
  CreateLabelReallocationRequest
> = z.object({
  links: z.lazy(() => CreateLabelReallocationLinks$outboundSchema),
  amount: z.lazy(() => CreateLabelReallocationAmount$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

export function createLabelReallocationRequestToJSON(
  createLabelReallocationRequest: CreateLabelReallocationRequest,
): string {
  return JSON.stringify(
    CreateLabelReallocationRequest$outboundSchema.parse(
      createLabelReallocationRequest,
    ),
  );
}

/** @internal */
export const CreateLabelReallocationResponse$inboundSchema: z.ZodType<
  CreateLabelReallocationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function createLabelReallocationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateLabelReallocationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateLabelReallocationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateLabelReallocationResponse' from JSON`,
  );
}
