/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Parameters for creating a beneficial owner
 */
export type CreateBeneficialOwnerForCustomerRequestBody =
  | models.CreateUSBeneficialOwner
  | models.CreateInternationalBeneficialOwner;

export type CreateBeneficialOwnerForCustomerRequest = {
  /**
   * Customer ID for which to create a Beneficial Owner
   */
  id: string;
  /**
   * Parameters for creating a beneficial owner
   */
  requestBody:
    | models.CreateUSBeneficialOwner
    | models.CreateInternationalBeneficialOwner;
};

export type CreateBeneficialOwnerForCustomerResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type CreateBeneficialOwnerForCustomerRequestBody$Outbound =
  | models.CreateUSBeneficialOwner$Outbound
  | models.CreateInternationalBeneficialOwner$Outbound;

/** @internal */
export const CreateBeneficialOwnerForCustomerRequestBody$outboundSchema:
  z.ZodType<
    CreateBeneficialOwnerForCustomerRequestBody$Outbound,
    z.ZodTypeDef,
    CreateBeneficialOwnerForCustomerRequestBody
  > = z.union([
    models.CreateUSBeneficialOwner$outboundSchema,
    models.CreateInternationalBeneficialOwner$outboundSchema,
  ]);

export function createBeneficialOwnerForCustomerRequestBodyToJSON(
  createBeneficialOwnerForCustomerRequestBody:
    CreateBeneficialOwnerForCustomerRequestBody,
): string {
  return JSON.stringify(
    CreateBeneficialOwnerForCustomerRequestBody$outboundSchema.parse(
      createBeneficialOwnerForCustomerRequestBody,
    ),
  );
}

/** @internal */
export type CreateBeneficialOwnerForCustomerRequest$Outbound = {
  id: string;
  RequestBody:
    | models.CreateUSBeneficialOwner$Outbound
    | models.CreateInternationalBeneficialOwner$Outbound;
};

/** @internal */
export const CreateBeneficialOwnerForCustomerRequest$outboundSchema: z.ZodType<
  CreateBeneficialOwnerForCustomerRequest$Outbound,
  z.ZodTypeDef,
  CreateBeneficialOwnerForCustomerRequest
> = z.object({
  id: z.string(),
  requestBody: z.union([
    models.CreateUSBeneficialOwner$outboundSchema,
    models.CreateInternationalBeneficialOwner$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function createBeneficialOwnerForCustomerRequestToJSON(
  createBeneficialOwnerForCustomerRequest:
    CreateBeneficialOwnerForCustomerRequest,
): string {
  return JSON.stringify(
    CreateBeneficialOwnerForCustomerRequest$outboundSchema.parse(
      createBeneficialOwnerForCustomerRequest,
    ),
  );
}

/** @internal */
export const CreateBeneficialOwnerForCustomerResponse$inboundSchema: z.ZodType<
  CreateBeneficialOwnerForCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function createBeneficialOwnerForCustomerResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateBeneficialOwnerForCustomerResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBeneficialOwnerForCustomerResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateBeneficialOwnerForCustomerResponse' from JSON`,
  );
}
