/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateLabelLedgerEntryAmount = {
  /**
   * Amount of funds to increase or decrease for a Label. To decrease funds in a Label a string numeric value will be supplied and prepended with a "-" operator.
   */
  value: string;
  /**
   * Currency code for the amount
   */
  currency: string;
};

/**
 * Parameters to create a label ledger entry
 */
export type CreateLabelLedgerEntryRequestBody = {
  amount: CreateLabelLedgerEntryAmount;
};

export type CreateLabelLedgerEntryRequest = {
  /**
   * The Id of the Label to update.
   */
  id: string;
  /**
   * Parameters to create a label ledger entry
   */
  requestBody: CreateLabelLedgerEntryRequestBody;
};

export type CreateLabelLedgerEntryResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type CreateLabelLedgerEntryAmount$Outbound = {
  value: string;
  currency: string;
};

/** @internal */
export const CreateLabelLedgerEntryAmount$outboundSchema: z.ZodType<
  CreateLabelLedgerEntryAmount$Outbound,
  z.ZodTypeDef,
  CreateLabelLedgerEntryAmount
> = z.object({
  value: z.string(),
  currency: z.string(),
});

export function createLabelLedgerEntryAmountToJSON(
  createLabelLedgerEntryAmount: CreateLabelLedgerEntryAmount,
): string {
  return JSON.stringify(
    CreateLabelLedgerEntryAmount$outboundSchema.parse(
      createLabelLedgerEntryAmount,
    ),
  );
}

/** @internal */
export type CreateLabelLedgerEntryRequestBody$Outbound = {
  amount: CreateLabelLedgerEntryAmount$Outbound;
};

/** @internal */
export const CreateLabelLedgerEntryRequestBody$outboundSchema: z.ZodType<
  CreateLabelLedgerEntryRequestBody$Outbound,
  z.ZodTypeDef,
  CreateLabelLedgerEntryRequestBody
> = z.object({
  amount: z.lazy(() => CreateLabelLedgerEntryAmount$outboundSchema),
});

export function createLabelLedgerEntryRequestBodyToJSON(
  createLabelLedgerEntryRequestBody: CreateLabelLedgerEntryRequestBody,
): string {
  return JSON.stringify(
    CreateLabelLedgerEntryRequestBody$outboundSchema.parse(
      createLabelLedgerEntryRequestBody,
    ),
  );
}

/** @internal */
export type CreateLabelLedgerEntryRequest$Outbound = {
  id: string;
  RequestBody: CreateLabelLedgerEntryRequestBody$Outbound;
};

/** @internal */
export const CreateLabelLedgerEntryRequest$outboundSchema: z.ZodType<
  CreateLabelLedgerEntryRequest$Outbound,
  z.ZodTypeDef,
  CreateLabelLedgerEntryRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => CreateLabelLedgerEntryRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function createLabelLedgerEntryRequestToJSON(
  createLabelLedgerEntryRequest: CreateLabelLedgerEntryRequest,
): string {
  return JSON.stringify(
    CreateLabelLedgerEntryRequest$outboundSchema.parse(
      createLabelLedgerEntryRequest,
    ),
  );
}

/** @internal */
export const CreateLabelLedgerEntryResponse$inboundSchema: z.ZodType<
  CreateLabelLedgerEntryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function createLabelLedgerEntryResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateLabelLedgerEntryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateLabelLedgerEntryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateLabelLedgerEntryResponse' from JSON`,
  );
}
