/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetExchangePartnerRequest = {
  /**
   * Exchange Partner resource unique identifier.
   */
  id: string;
};

/** @internal */
export type GetExchangePartnerRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetExchangePartnerRequest$outboundSchema: z.ZodType<
  GetExchangePartnerRequest$Outbound,
  z.ZodTypeDef,
  GetExchangePartnerRequest
> = z.object({
  id: z.string(),
});

export function getExchangePartnerRequestToJSON(
  getExchangePartnerRequest: GetExchangePartnerRequest,
): string {
  return JSON.stringify(
    GetExchangePartnerRequest$outboundSchema.parse(getExchangePartnerRequest),
  );
}
