/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetMicroDepositsRequest = {
  /**
   * The ID of the FS that previously had micro-deposits initiated
   */
  id: string;
};

export type Failure = {
  code?: string | undefined;
  description?: string | undefined;
};

/**
 * ACH details for the first micro-deposit
 */
export type Deposit1 = {
  /**
   * A unique identifier for tracing the ACH transaction through the banking network. Used for transaction tracking and reconciliation purposes
   */
  traceId: string;
};

/**
 * ACH details for the second micro-deposit
 */
export type Deposit2 = {
  /**
   * A unique identifier for tracing the ACH transaction through the banking network. Used for transaction tracking and reconciliation purposes
   */
  traceId: string;
};

/**
 * ACH details for each micro-deposit. Optional; only returned when ACH details are available for the micro-deposits. `deposit1` or `deposit2` may be omitted if details for that deposit are unavailable.
 */
export type GetMicroDepositsAchDetails = {
  /**
   * ACH details for the first micro-deposit
   */
  deposit1?: Deposit1 | undefined;
  /**
   * ACH details for the second micro-deposit
   */
  deposit2?: Deposit2 | undefined;
};

/**
 * successful operation
 */
export type GetMicroDepositsResponse = {
  links?: { [k: string]: models.HalLink } | undefined;
  created?: Date | undefined;
  status?: string | undefined;
  failure?: Failure | undefined;
  /**
   * ACH details for each micro-deposit. Optional; only returned when ACH details are available for the micro-deposits. `deposit1` or `deposit2` may be omitted if details for that deposit are unavailable.
   */
  achDetails?: GetMicroDepositsAchDetails | undefined;
};

/** @internal */
export type GetMicroDepositsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetMicroDepositsRequest$outboundSchema: z.ZodType<
  GetMicroDepositsRequest$Outbound,
  z.ZodTypeDef,
  GetMicroDepositsRequest
> = z.object({
  id: z.string(),
});

export function getMicroDepositsRequestToJSON(
  getMicroDepositsRequest: GetMicroDepositsRequest,
): string {
  return JSON.stringify(
    GetMicroDepositsRequest$outboundSchema.parse(getMicroDepositsRequest),
  );
}

/** @internal */
export const Failure$inboundSchema: z.ZodType<Failure, z.ZodTypeDef, unknown> =
  z.object({
    code: z.string().optional(),
    description: z.string().optional(),
  });

export function failureFromJSON(
  jsonString: string,
): SafeParseResult<Failure, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Failure$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Failure' from JSON`,
  );
}

/** @internal */
export const Deposit1$inboundSchema: z.ZodType<
  Deposit1,
  z.ZodTypeDef,
  unknown
> = z.object({
  traceId: z.string(),
});

export function deposit1FromJSON(
  jsonString: string,
): SafeParseResult<Deposit1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Deposit1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Deposit1' from JSON`,
  );
}

/** @internal */
export const Deposit2$inboundSchema: z.ZodType<
  Deposit2,
  z.ZodTypeDef,
  unknown
> = z.object({
  traceId: z.string(),
});

export function deposit2FromJSON(
  jsonString: string,
): SafeParseResult<Deposit2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Deposit2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Deposit2' from JSON`,
  );
}

/** @internal */
export const GetMicroDepositsAchDetails$inboundSchema: z.ZodType<
  GetMicroDepositsAchDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  deposit1: z.lazy(() => Deposit1$inboundSchema).optional(),
  deposit2: z.lazy(() => Deposit2$inboundSchema).optional(),
});

export function getMicroDepositsAchDetailsFromJSON(
  jsonString: string,
): SafeParseResult<GetMicroDepositsAchDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMicroDepositsAchDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMicroDepositsAchDetails' from JSON`,
  );
}

/** @internal */
export const GetMicroDepositsResponse$inboundSchema: z.ZodType<
  GetMicroDepositsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(models.HalLink$inboundSchema).optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  status: z.string().optional(),
  failure: z.lazy(() => Failure$inboundSchema).optional(),
  achDetails: z.lazy(() => GetMicroDepositsAchDetails$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

export function getMicroDepositsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetMicroDepositsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMicroDepositsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMicroDepositsResponse' from JSON`,
  );
}
