/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetTransferFailureReasonRequest = {
  /**
   * Transfer unique identifier
   */
  id: string;
};

/**
 * successful operation
 */
export type GetTransferFailureReasonResponse = {
  links?: { [k: string]: models.HalLink } | undefined;
  code: string;
  description: string;
  explanation?: string | undefined;
};

/** @internal */
export type GetTransferFailureReasonRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTransferFailureReasonRequest$outboundSchema: z.ZodType<
  GetTransferFailureReasonRequest$Outbound,
  z.ZodTypeDef,
  GetTransferFailureReasonRequest
> = z.object({
  id: z.string(),
});

export function getTransferFailureReasonRequestToJSON(
  getTransferFailureReasonRequest: GetTransferFailureReasonRequest,
): string {
  return JSON.stringify(
    GetTransferFailureReasonRequest$outboundSchema.parse(
      getTransferFailureReasonRequest,
    ),
  );
}

/** @internal */
export const GetTransferFailureReasonResponse$inboundSchema: z.ZodType<
  GetTransferFailureReasonResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(models.HalLink$inboundSchema).optional(),
  code: z.string(),
  description: z.string(),
  explanation: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

export function getTransferFailureReasonResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTransferFailureReasonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransferFailureReasonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransferFailureReasonResponse' from JSON`,
  );
}
