/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListLabelLedgerEntriesRequest = {
  /**
   * A label unique identifier
   */
  id: string;
  /**
   * How many results to return
   */
  limit?: number | undefined;
  /**
   * How many results to skip
   */
  offset?: number | undefined;
};

/** @internal */
export type ListLabelLedgerEntriesRequest$Outbound = {
  id: string;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const ListLabelLedgerEntriesRequest$outboundSchema: z.ZodType<
  ListLabelLedgerEntriesRequest$Outbound,
  z.ZodTypeDef,
  ListLabelLedgerEntriesRequest
> = z.object({
  id: z.string(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
});

export function listLabelLedgerEntriesRequestToJSON(
  listLabelLedgerEntriesRequest: ListLabelLedgerEntriesRequest,
): string {
  return JSON.stringify(
    ListLabelLedgerEntriesRequest$outboundSchema.parse(
      listLabelLedgerEntriesRequest,
    ),
  );
}
