/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CardMissingRequiredFieldsErrorError = {
  code: string;
  message: string;
  path: string;
};

export type CardMissingRequiredFieldsErrorEmbedded = {
  errors: Array<CardMissingRequiredFieldsErrorError>;
};

/** @internal */
export const CardMissingRequiredFieldsErrorError$inboundSchema: z.ZodType<
  CardMissingRequiredFieldsErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
  path: z.string(),
});

export function cardMissingRequiredFieldsErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<CardMissingRequiredFieldsErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CardMissingRequiredFieldsErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardMissingRequiredFieldsErrorError' from JSON`,
  );
}

/** @internal */
export const CardMissingRequiredFieldsErrorEmbedded$inboundSchema: z.ZodType<
  CardMissingRequiredFieldsErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(
    z.lazy(() => CardMissingRequiredFieldsErrorError$inboundSchema),
  ),
});

export function cardMissingRequiredFieldsErrorEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<CardMissingRequiredFieldsErrorEmbedded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CardMissingRequiredFieldsErrorEmbedded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardMissingRequiredFieldsErrorEmbedded' from JSON`,
  );
}
