/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateCustomerExchangeSessionForCardExchangePartner = {
  /**
   * URL of the cards exchange partner. Use `GET /exchange-partners` to locate it.
   */
  href: string;
};

export type CreateCustomerExchangeSessionForCardLinks = {
  exchangePartner: CreateCustomerExchangeSessionForCardExchangePartner;
};

/**
 * Optional. Opt into Account Name Inquiry (ANI) for this session by providing the expected
 *
 * @remarks
 * cardholder name. Retrieve the resulting match on the Exchange with `GET /exchanges/{id}`.
 */
export type CreateCustomerExchangeSessionForCardCardDetails = {
  /**
   * The cardholder first name you expect on the card.
   */
  firstName: string;
  /**
   * The cardholder last name you expect on the card.
   */
  lastName: string;
  /**
   * Set to `true` to request an Account Name Inquiry (ANI) name-match check on the card.
   */
  accountNameInquiry: boolean;
};

/**
 * Create an exchange session for debit card capture (Push to Card).
 *
 * @remarks
 *
 * Optionally opt into Account Name Inquiry (ANI) by passing `cardDetails` with the cardholder
 * name you expect on the card. The name-match result is returned on the resulting Exchange as
 * `cardDetails.accountNameInquiry`, giving you an early signal of fraudulent card usage before
 * you create a funding source.
 */
export type CreateCustomerExchangeSessionForCard = {
  links: CreateCustomerExchangeSessionForCardLinks;
  /**
   * Optional. Opt into Account Name Inquiry (ANI) for this session by providing the expected
   *
   * @remarks
   * cardholder name. Retrieve the resulting match on the Exchange with `GET /exchanges/{id}`.
   */
  cardDetails?: CreateCustomerExchangeSessionForCardCardDetails | undefined;
};

/** @internal */
export type CreateCustomerExchangeSessionForCardExchangePartner$Outbound = {
  href: string;
};

/** @internal */
export const CreateCustomerExchangeSessionForCardExchangePartner$outboundSchema:
  z.ZodType<
    CreateCustomerExchangeSessionForCardExchangePartner$Outbound,
    z.ZodTypeDef,
    CreateCustomerExchangeSessionForCardExchangePartner
  > = z.object({
    href: z.string(),
  });

export function createCustomerExchangeSessionForCardExchangePartnerToJSON(
  createCustomerExchangeSessionForCardExchangePartner:
    CreateCustomerExchangeSessionForCardExchangePartner,
): string {
  return JSON.stringify(
    CreateCustomerExchangeSessionForCardExchangePartner$outboundSchema.parse(
      createCustomerExchangeSessionForCardExchangePartner,
    ),
  );
}

/** @internal */
export type CreateCustomerExchangeSessionForCardLinks$Outbound = {
  "exchange-partner":
    CreateCustomerExchangeSessionForCardExchangePartner$Outbound;
};

/** @internal */
export const CreateCustomerExchangeSessionForCardLinks$outboundSchema:
  z.ZodType<
    CreateCustomerExchangeSessionForCardLinks$Outbound,
    z.ZodTypeDef,
    CreateCustomerExchangeSessionForCardLinks
  > = z.object({
    exchangePartner: z.lazy(() =>
      CreateCustomerExchangeSessionForCardExchangePartner$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      exchangePartner: "exchange-partner",
    });
  });

export function createCustomerExchangeSessionForCardLinksToJSON(
  createCustomerExchangeSessionForCardLinks:
    CreateCustomerExchangeSessionForCardLinks,
): string {
  return JSON.stringify(
    CreateCustomerExchangeSessionForCardLinks$outboundSchema.parse(
      createCustomerExchangeSessionForCardLinks,
    ),
  );
}

/** @internal */
export type CreateCustomerExchangeSessionForCardCardDetails$Outbound = {
  firstName: string;
  lastName: string;
  accountNameInquiry: boolean;
};

/** @internal */
export const CreateCustomerExchangeSessionForCardCardDetails$outboundSchema:
  z.ZodType<
    CreateCustomerExchangeSessionForCardCardDetails$Outbound,
    z.ZodTypeDef,
    CreateCustomerExchangeSessionForCardCardDetails
  > = z.object({
    firstName: z.string(),
    lastName: z.string(),
    accountNameInquiry: z.boolean(),
  });

export function createCustomerExchangeSessionForCardCardDetailsToJSON(
  createCustomerExchangeSessionForCardCardDetails:
    CreateCustomerExchangeSessionForCardCardDetails,
): string {
  return JSON.stringify(
    CreateCustomerExchangeSessionForCardCardDetails$outboundSchema.parse(
      createCustomerExchangeSessionForCardCardDetails,
    ),
  );
}

/** @internal */
export type CreateCustomerExchangeSessionForCard$Outbound = {
  _links: CreateCustomerExchangeSessionForCardLinks$Outbound;
  cardDetails?:
    | CreateCustomerExchangeSessionForCardCardDetails$Outbound
    | undefined;
};

/** @internal */
export const CreateCustomerExchangeSessionForCard$outboundSchema: z.ZodType<
  CreateCustomerExchangeSessionForCard$Outbound,
  z.ZodTypeDef,
  CreateCustomerExchangeSessionForCard
> = z.object({
  links: z.lazy(() => CreateCustomerExchangeSessionForCardLinks$outboundSchema),
  cardDetails: z.lazy(() =>
    CreateCustomerExchangeSessionForCardCardDetails$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

export function createCustomerExchangeSessionForCardToJSON(
  createCustomerExchangeSessionForCard: CreateCustomerExchangeSessionForCard,
): string {
  return JSON.stringify(
    CreateCustomerExchangeSessionForCard$outboundSchema.parse(
      createCustomerExchangeSessionForCard,
    ),
  );
}
