/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type CreateReAuthExchangeSessionWithRedirectRedirectUrl = {
  /**
   * Required for Plaid mobile sessions
   */
  href: string;
};

export type CreateReAuthExchangeSessionWithRedirectLinks = {
  redirectUrl: CreateReAuthExchangeSessionWithRedirectRedirectUrl;
};

/**
 * Create re-auth exchange session with redirect URL (required for mobile sessions with Plaid)
 */
export type CreateReAuthExchangeSessionWithRedirect = {
  links: CreateReAuthExchangeSessionWithRedirectLinks;
};

/** @internal */
export type CreateReAuthExchangeSessionWithRedirectRedirectUrl$Outbound = {
  href: string;
};

/** @internal */
export const CreateReAuthExchangeSessionWithRedirectRedirectUrl$outboundSchema:
  z.ZodType<
    CreateReAuthExchangeSessionWithRedirectRedirectUrl$Outbound,
    z.ZodTypeDef,
    CreateReAuthExchangeSessionWithRedirectRedirectUrl
  > = z.object({
    href: z.string(),
  });

export function createReAuthExchangeSessionWithRedirectRedirectUrlToJSON(
  createReAuthExchangeSessionWithRedirectRedirectUrl:
    CreateReAuthExchangeSessionWithRedirectRedirectUrl,
): string {
  return JSON.stringify(
    CreateReAuthExchangeSessionWithRedirectRedirectUrl$outboundSchema.parse(
      createReAuthExchangeSessionWithRedirectRedirectUrl,
    ),
  );
}

/** @internal */
export type CreateReAuthExchangeSessionWithRedirectLinks$Outbound = {
  "redirect-url": CreateReAuthExchangeSessionWithRedirectRedirectUrl$Outbound;
};

/** @internal */
export const CreateReAuthExchangeSessionWithRedirectLinks$outboundSchema:
  z.ZodType<
    CreateReAuthExchangeSessionWithRedirectLinks$Outbound,
    z.ZodTypeDef,
    CreateReAuthExchangeSessionWithRedirectLinks
  > = z.object({
    redirectUrl: z.lazy(() =>
      CreateReAuthExchangeSessionWithRedirectRedirectUrl$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      redirectUrl: "redirect-url",
    });
  });

export function createReAuthExchangeSessionWithRedirectLinksToJSON(
  createReAuthExchangeSessionWithRedirectLinks:
    CreateReAuthExchangeSessionWithRedirectLinks,
): string {
  return JSON.stringify(
    CreateReAuthExchangeSessionWithRedirectLinks$outboundSchema.parse(
      createReAuthExchangeSessionWithRedirectLinks,
    ),
  );
}

/** @internal */
export type CreateReAuthExchangeSessionWithRedirect$Outbound = {
  _links: CreateReAuthExchangeSessionWithRedirectLinks$Outbound;
};

/** @internal */
export const CreateReAuthExchangeSessionWithRedirect$outboundSchema: z.ZodType<
  CreateReAuthExchangeSessionWithRedirect$Outbound,
  z.ZodTypeDef,
  CreateReAuthExchangeSessionWithRedirect
> = z.object({
  links: z.lazy(() =>
    CreateReAuthExchangeSessionWithRedirectLinks$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

export function createReAuthExchangeSessionWithRedirectToJSON(
  createReAuthExchangeSessionWithRedirect:
    CreateReAuthExchangeSessionWithRedirect,
): string {
  return JSON.stringify(
    CreateReAuthExchangeSessionWithRedirect$outboundSchema.parse(
      createReAuthExchangeSessionWithRedirect,
    ),
  );
}
