/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Event, Event$inboundSchema } from "./event.js";
import { HalLink, HalLink$inboundSchema } from "./hallink.js";

export type EventsLinks = {};

export type EventsEmbedded = {
  events?: Array<Event> | undefined;
};

export type Events = {
  links?: EventsLinks | undefined;
  additionalProperties?: HalLink | undefined;
  embedded?: EventsEmbedded | undefined;
  total?: number | undefined;
};

/** @internal */
export const EventsLinks$inboundSchema: z.ZodType<
  EventsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function eventsLinksFromJSON(
  jsonString: string,
): SafeParseResult<EventsLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsLinks' from JSON`,
  );
}

/** @internal */
export const EventsEmbedded$inboundSchema: z.ZodType<
  EventsEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  events: z.array(Event$inboundSchema).optional(),
});

export function eventsEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<EventsEmbedded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsEmbedded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsEmbedded' from JSON`,
  );
}

/** @internal */
export const Events$inboundSchema: z.ZodType<Events, z.ZodTypeDef, unknown> = z
  .object({
    _links: z.lazy(() => EventsLinks$inboundSchema).optional(),
    additionalProperties: HalLink$inboundSchema.optional(),
    _embedded: z.lazy(() => EventsEmbedded$inboundSchema).optional(),
    total: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      "_links": "links",
      "_embedded": "embedded",
    });
  });

export function eventsFromJSON(
  jsonString: string,
): SafeParseResult<Events, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Events$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Events' from JSON`,
  );
}
