/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ExchangePartner,
  ExchangePartner$inboundSchema,
} from "./exchangepartner.js";
import { HalLink, HalLink$inboundSchema } from "./hallink.js";

export type ExchangePartnersEmbedded = {
  exchangePartners?: Array<ExchangePartner> | undefined;
};

export type ExchangePartners = {
  links?: { [k: string]: HalLink } | undefined;
  embedded?: ExchangePartnersEmbedded | undefined;
  total?: number | undefined;
};

/** @internal */
export const ExchangePartnersEmbedded$inboundSchema: z.ZodType<
  ExchangePartnersEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  "exchange-partners": z.array(ExchangePartner$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "exchange-partners": "exchangePartners",
  });
});

export function exchangePartnersEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<ExchangePartnersEmbedded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExchangePartnersEmbedded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExchangePartnersEmbedded' from JSON`,
  );
}

/** @internal */
export const ExchangePartners$inboundSchema: z.ZodType<
  ExchangePartners,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$inboundSchema).optional(),
  _embedded: z.lazy(() => ExchangePartnersEmbedded$inboundSchema).optional(),
  total: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
    "_embedded": "embedded",
  });
});

export function exchangePartnersFromJSON(
  jsonString: string,
): SafeParseResult<ExchangePartners, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExchangePartners$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExchangePartners' from JSON`,
  );
}
