/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ExpiredKbaSessionError = {
  code: string;
  message: string;
};

/** @internal */
export const ExpiredKbaSessionError$inboundSchema: z.ZodType<
  ExpiredKbaSessionError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type ExpiredKbaSessionError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const ExpiredKbaSessionError$outboundSchema: z.ZodType<
  ExpiredKbaSessionError$Outbound,
  z.ZodTypeDef,
  ExpiredKbaSessionError
> = z.object({
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExpiredKbaSessionError$ {
  /** @deprecated use `ExpiredKbaSessionError$inboundSchema` instead. */
  export const inboundSchema = ExpiredKbaSessionError$inboundSchema;
  /** @deprecated use `ExpiredKbaSessionError$outboundSchema` instead. */
  export const outboundSchema = ExpiredKbaSessionError$outboundSchema;
  /** @deprecated use `ExpiredKbaSessionError$Outbound` instead. */
  export type Outbound = ExpiredKbaSessionError$Outbound;
}

export function expiredKbaSessionErrorToJSON(
  expiredKbaSessionError: ExpiredKbaSessionError,
): string {
  return JSON.stringify(
    ExpiredKbaSessionError$outboundSchema.parse(expiredKbaSessionError),
  );
}

export function expiredKbaSessionErrorFromJSON(
  jsonString: string,
): SafeParseResult<ExpiredKbaSessionError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpiredKbaSessionError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpiredKbaSessionError' from JSON`,
  );
}
