/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type HalLink = {
  href?: string | undefined;
  type?: string | undefined;
  resourceType?: string | undefined;
};

/** @internal */
export const HalLink$inboundSchema: z.ZodType<HalLink, z.ZodTypeDef, unknown> =
  z.object({
    href: z.string().optional(),
    type: z.string().optional(),
    "resource-type": z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "resource-type": "resourceType",
    });
  });

export function halLinkFromJSON(
  jsonString: string,
): SafeParseResult<HalLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HalLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HalLink' from JSON`,
  );
}
