/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type IncompatibleSourceForRtpDestinationErrorLinks = {};

export type IncompatibleSourceForRtpDestinationErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  links?: IncompatibleSourceForRtpDestinationErrorLinks | undefined;
};

export type IncompatibleSourceForRtpDestinationErrorEmbedded = {
  errors?: Array<IncompatibleSourceForRtpDestinationErrorError> | undefined;
};

/** @internal */
export const IncompatibleSourceForRtpDestinationErrorLinks$inboundSchema:
  z.ZodType<
    IncompatibleSourceForRtpDestinationErrorLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function incompatibleSourceForRtpDestinationErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<
  IncompatibleSourceForRtpDestinationErrorLinks,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncompatibleSourceForRtpDestinationErrorLinks$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncompatibleSourceForRtpDestinationErrorLinks' from JSON`,
  );
}

/** @internal */
export const IncompatibleSourceForRtpDestinationErrorError$inboundSchema:
  z.ZodType<
    IncompatibleSourceForRtpDestinationErrorError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
    path: z.string().optional(),
    _links: z.lazy(() =>
      IncompatibleSourceForRtpDestinationErrorLinks$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "_links": "links",
    });
  });

export function incompatibleSourceForRtpDestinationErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  IncompatibleSourceForRtpDestinationErrorError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncompatibleSourceForRtpDestinationErrorError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncompatibleSourceForRtpDestinationErrorError' from JSON`,
  );
}

/** @internal */
export const IncompatibleSourceForRtpDestinationErrorEmbedded$inboundSchema:
  z.ZodType<
    IncompatibleSourceForRtpDestinationErrorEmbedded,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(
      z.lazy(() => IncompatibleSourceForRtpDestinationErrorError$inboundSchema),
    ).optional(),
  });

export function incompatibleSourceForRtpDestinationErrorEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<
  IncompatibleSourceForRtpDestinationErrorEmbedded,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncompatibleSourceForRtpDestinationErrorEmbedded$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncompatibleSourceForRtpDestinationErrorEmbedded' from JSON`,
  );
}
