/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InvalidKbaSessionError = {
  code: string;
  message: string;
};

/** @internal */
export const InvalidKbaSessionError$inboundSchema: z.ZodType<
  InvalidKbaSessionError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string(),
});

/** @internal */
export type InvalidKbaSessionError$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const InvalidKbaSessionError$outboundSchema: z.ZodType<
  InvalidKbaSessionError$Outbound,
  z.ZodTypeDef,
  InvalidKbaSessionError
> = z.object({
  code: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InvalidKbaSessionError$ {
  /** @deprecated use `InvalidKbaSessionError$inboundSchema` instead. */
  export const inboundSchema = InvalidKbaSessionError$inboundSchema;
  /** @deprecated use `InvalidKbaSessionError$outboundSchema` instead. */
  export const outboundSchema = InvalidKbaSessionError$outboundSchema;
  /** @deprecated use `InvalidKbaSessionError$Outbound` instead. */
  export type Outbound = InvalidKbaSessionError$Outbound;
}

export function invalidKbaSessionErrorToJSON(
  invalidKbaSessionError: InvalidKbaSessionError,
): string {
  return JSON.stringify(
    InvalidKbaSessionError$outboundSchema.parse(invalidKbaSessionError),
  );
}

export function invalidKbaSessionErrorFromJSON(
  jsonString: string,
): SafeParseResult<InvalidKbaSessionError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvalidKbaSessionError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidKbaSessionError' from JSON`,
  );
}
