/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InvalidSourceFundingSourceErrorLinks = {};

export type InvalidSourceFundingSourceErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  links?: InvalidSourceFundingSourceErrorLinks | undefined;
};

export type InvalidSourceFundingSourceErrorEmbedded = {
  errors?: Array<InvalidSourceFundingSourceErrorError> | undefined;
};

/** @internal */
export const InvalidSourceFundingSourceErrorLinks$inboundSchema: z.ZodType<
  InvalidSourceFundingSourceErrorLinks,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function invalidSourceFundingSourceErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<InvalidSourceFundingSourceErrorLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      InvalidSourceFundingSourceErrorLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidSourceFundingSourceErrorLinks' from JSON`,
  );
}

/** @internal */
export const InvalidSourceFundingSourceErrorError$inboundSchema: z.ZodType<
  InvalidSourceFundingSourceErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  message: z.string().optional(),
  path: z.string().optional(),
  _links: z.lazy(() => InvalidSourceFundingSourceErrorLinks$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

export function invalidSourceFundingSourceErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InvalidSourceFundingSourceErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      InvalidSourceFundingSourceErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidSourceFundingSourceErrorError' from JSON`,
  );
}

/** @internal */
export const InvalidSourceFundingSourceErrorEmbedded$inboundSchema: z.ZodType<
  InvalidSourceFundingSourceErrorEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(
    z.lazy(() => InvalidSourceFundingSourceErrorError$inboundSchema),
  ).optional(),
});

export function invalidSourceFundingSourceErrorEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<
  InvalidSourceFundingSourceErrorEmbedded,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      InvalidSourceFundingSourceErrorEmbedded$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'InvalidSourceFundingSourceErrorEmbedded' from JSON`,
  );
}
