/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { smartUnion } from "../types/smartUnion.js";
import {
  SandboxSimulationBankProcessingRequest,
  SandboxSimulationBankProcessingRequest$Outbound,
  SandboxSimulationBankProcessingRequest$outboundSchema,
} from "./sandboxsimulationbankprocessingrequest.js";
import {
  SandboxSimulationCustomerVerificationRequest,
  SandboxSimulationCustomerVerificationRequest$Outbound,
  SandboxSimulationCustomerVerificationRequest$outboundSchema,
} from "./sandboxsimulationcustomerverificationrequest.js";
import {
  SandboxSimulationVirtualAccountTransfersRequest,
  SandboxSimulationVirtualAccountTransfersRequest$Outbound,
  SandboxSimulationVirtualAccountTransfersRequest$outboundSchema,
} from "./sandboxsimulationvirtualaccounttransfersrequest.js";

/**
 * Bank transfer processing (omit body or `{}`), VAN transfer simulation (`type` virtual + transfers), or
 *
 * @remarks
 * verification directive simulation (`type` customer-verification, customer link, and errorCode). Typed bodies
 * are mutually exclusive; use only an omitted body or `{}` for bank processing.
 */
export type SandboxSimulationRequest =
  | SandboxSimulationCustomerVerificationRequest
  | SandboxSimulationVirtualAccountTransfersRequest
  | SandboxSimulationBankProcessingRequest;

/** @internal */
export type SandboxSimulationRequest$Outbound =
  | SandboxSimulationCustomerVerificationRequest$Outbound
  | SandboxSimulationVirtualAccountTransfersRequest$Outbound
  | SandboxSimulationBankProcessingRequest$Outbound;

/** @internal */
export const SandboxSimulationRequest$outboundSchema: z.ZodType<
  SandboxSimulationRequest$Outbound,
  z.ZodTypeDef,
  SandboxSimulationRequest
> = smartUnion([
  SandboxSimulationCustomerVerificationRequest$outboundSchema,
  SandboxSimulationVirtualAccountTransfersRequest$outboundSchema,
  SandboxSimulationBankProcessingRequest$outboundSchema,
]);

export function sandboxSimulationRequestToJSON(
  sandboxSimulationRequest: SandboxSimulationRequest,
): string {
  return JSON.stringify(
    SandboxSimulationRequest$outboundSchema.parse(sandboxSimulationRequest),
  );
}
