/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for updating information of a Verified bank funding source
 */
export type UpdateVerifiedBank = {
  name: string;
};

/** @internal */
export type UpdateVerifiedBank$Outbound = {
  name: string;
};

/** @internal */
export const UpdateVerifiedBank$outboundSchema: z.ZodType<
  UpdateVerifiedBank$Outbound,
  z.ZodTypeDef,
  UpdateVerifiedBank
> = z.object({
  name: z.string(),
});

export function updateVerifiedBankToJSON(
  updateVerifiedBank: UpdateVerifiedBank,
): string {
  return JSON.stringify(
    UpdateVerifiedBank$outboundSchema.parse(updateVerifiedBank),
  );
}
