/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { HalLink, HalLink$inboundSchema } from "./hallink.js";

export const VerifiedBusinessCustomerType = {
  Business: "business",
} as const;
export type VerifiedBusinessCustomerType = ClosedEnum<
  typeof VerifiedBusinessCustomerType
>;

export const VerifiedBusinessCustomerStatus = {
  Verified: "verified",
  Suspended: "suspended",
  Deactivated: "deactivated",
  Document: "document",
  Retry: "retry",
} as const;
export type VerifiedBusinessCustomerStatus = ClosedEnum<
  typeof VerifiedBusinessCustomerStatus
>;

export const VerifiedBusinessCustomerBusinessType = {
  Llc: "llc",
  Corporation: "corporation",
  Partnership: "partnership",
} as const;
export type VerifiedBusinessCustomerBusinessType = ClosedEnum<
  typeof VerifiedBusinessCustomerBusinessType
>;

export type Address = {
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  city?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  stateProvinceRegion?: string | undefined;
};

export type VerifiedBusinessCustomerController = {
  firstName: string;
  lastName: string;
  title: string;
  address: Address;
};

/**
 * Verified business customer (LLC, Corporation, Partnership) - distinguished from VerifiedSolePropCustomer by presence of a controller object
 */
export type VerifiedBusinessCustomer = {
  links: { [k: string]: HalLink };
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  correlationId?: string | undefined;
  created: Date;
  type: VerifiedBusinessCustomerType;
  status: VerifiedBusinessCustomerStatus;
  address1: string;
  address2?: string | undefined;
  city: string;
  state: string;
  postalCode: string;
  phone?: string | undefined;
  website?: string | undefined;
  businessName: string;
  doingBusinessAs?: string | undefined;
  businessType: VerifiedBusinessCustomerBusinessType;
  businessClassification: string;
  controller: VerifiedBusinessCustomerController;
};

/** @internal */
export const VerifiedBusinessCustomerType$inboundSchema: z.ZodNativeEnum<
  typeof VerifiedBusinessCustomerType
> = z.nativeEnum(VerifiedBusinessCustomerType);

/** @internal */
export const VerifiedBusinessCustomerStatus$inboundSchema: z.ZodNativeEnum<
  typeof VerifiedBusinessCustomerStatus
> = z.nativeEnum(VerifiedBusinessCustomerStatus);

/** @internal */
export const VerifiedBusinessCustomerBusinessType$inboundSchema:
  z.ZodNativeEnum<typeof VerifiedBusinessCustomerBusinessType> = z.nativeEnum(
    VerifiedBusinessCustomerBusinessType,
  );

/** @internal */
export const Address$inboundSchema: z.ZodType<Address, z.ZodTypeDef, unknown> =
  z.object({
    address1: z.string().optional(),
    address2: z.string().optional(),
    address3: z.string().optional(),
    city: z.string().optional(),
    postalCode: z.string().optional(),
    country: z.string().optional(),
    stateProvinceRegion: z.string().optional(),
  });

export function addressFromJSON(
  jsonString: string,
): SafeParseResult<Address, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Address$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Address' from JSON`,
  );
}

/** @internal */
export const VerifiedBusinessCustomerController$inboundSchema: z.ZodType<
  VerifiedBusinessCustomerController,
  z.ZodTypeDef,
  unknown
> = z.object({
  firstName: z.string(),
  lastName: z.string(),
  title: z.string(),
  address: z.lazy(() => Address$inboundSchema),
});

export function verifiedBusinessCustomerControllerFromJSON(
  jsonString: string,
): SafeParseResult<VerifiedBusinessCustomerController, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VerifiedBusinessCustomerController$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifiedBusinessCustomerController' from JSON`,
  );
}

/** @internal */
export const VerifiedBusinessCustomer$inboundSchema: z.ZodType<
  VerifiedBusinessCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({
  _links: z.record(HalLink$inboundSchema),
  id: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
  correlationId: z.string().optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  type: VerifiedBusinessCustomerType$inboundSchema,
  status: VerifiedBusinessCustomerStatus$inboundSchema,
  address1: z.string(),
  address2: z.string().optional(),
  city: z.string(),
  state: z.string(),
  postalCode: z.string(),
  phone: z.string().optional(),
  website: z.string().optional(),
  businessName: z.string(),
  doingBusinessAs: z.string().optional(),
  businessType: VerifiedBusinessCustomerBusinessType$inboundSchema,
  businessClassification: z.string(),
  controller: z.lazy(() => VerifiedBusinessCustomerController$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

export function verifiedBusinessCustomerFromJSON(
  jsonString: string,
): SafeParseResult<VerifiedBusinessCustomer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerifiedBusinessCustomer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifiedBusinessCustomer' from JSON`,
  );
}
