/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type WithdrawRtpUnverifiedSenderNotSupportedErrorLinks = {};

export type WithdrawRtpUnverifiedSenderNotSupportedErrorError = {
  code?: string | undefined;
  message?: string | undefined;
  path?: string | undefined;
  links?: WithdrawRtpUnverifiedSenderNotSupportedErrorLinks | undefined;
};

export type WithdrawRtpUnverifiedSenderNotSupportedErrorEmbedded = {
  errors?: Array<WithdrawRtpUnverifiedSenderNotSupportedErrorError> | undefined;
};

/** @internal */
export const WithdrawRtpUnverifiedSenderNotSupportedErrorLinks$inboundSchema:
  z.ZodType<
    WithdrawRtpUnverifiedSenderNotSupportedErrorLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function withdrawRtpUnverifiedSenderNotSupportedErrorLinksFromJSON(
  jsonString: string,
): SafeParseResult<
  WithdrawRtpUnverifiedSenderNotSupportedErrorLinks,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WithdrawRtpUnverifiedSenderNotSupportedErrorLinks$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WithdrawRtpUnverifiedSenderNotSupportedErrorLinks' from JSON`,
  );
}

/** @internal */
export const WithdrawRtpUnverifiedSenderNotSupportedErrorError$inboundSchema:
  z.ZodType<
    WithdrawRtpUnverifiedSenderNotSupportedErrorError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: z.string().optional(),
    message: z.string().optional(),
    path: z.string().optional(),
    _links: z.lazy(() =>
      WithdrawRtpUnverifiedSenderNotSupportedErrorLinks$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "_links": "links",
    });
  });

export function withdrawRtpUnverifiedSenderNotSupportedErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  WithdrawRtpUnverifiedSenderNotSupportedErrorError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WithdrawRtpUnverifiedSenderNotSupportedErrorError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WithdrawRtpUnverifiedSenderNotSupportedErrorError' from JSON`,
  );
}

/** @internal */
export const WithdrawRtpUnverifiedSenderNotSupportedErrorEmbedded$inboundSchema:
  z.ZodType<
    WithdrawRtpUnverifiedSenderNotSupportedErrorEmbedded,
    z.ZodTypeDef,
    unknown
  > = z.object({
    errors: z.array(
      z.lazy(() =>
        WithdrawRtpUnverifiedSenderNotSupportedErrorError$inboundSchema
      ),
    ).optional(),
  });

export function withdrawRtpUnverifiedSenderNotSupportedErrorEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<
  WithdrawRtpUnverifiedSenderNotSupportedErrorEmbedded,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WithdrawRtpUnverifiedSenderNotSupportedErrorEmbedded$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WithdrawRtpUnverifiedSenderNotSupportedErrorEmbedded' from JSON`,
  );
}
